// Keyglove controller source code - KGAPI "feedback" protocol command parser
// 2014-11-03 by Jeff Rowberg <jeff@rowberg.net>
// Updates should (hopefully) always be available at https://github.com/jrowberg/keyglove

/* ============================================
Controller code is placed under the MIT license
Copyright (c) 2014 Jeff Rowberg

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
===============================================
*/

/**
 * @file support_protocol_feedback.h
 * @brief KGAPI "feedback" protocol command parser
 * @author Jeff Rowberg
 * @date 2014-11-03
 *
 * This file implements subsystem-specific command processing functions for the
 * "feedback" part of the KGAPI protocol.
 *
 * Normally it is not necessary to edit this file. (It is also autogenerated.)
 */

#ifndef _SUPPORT_PROTOCOL_FEEDBACK_H_
#define _SUPPORT_PROTOCOL_FEEDBACK_H_

/* =========================== */
/* KGAPI CONSTANT DECLARATIONS */
/* =========================== */

#define KG_PACKET_ID_CMD_FEEDBACK_GET_BLINK_MODE            0x01
#define KG_PACKET_ID_CMD_FEEDBACK_SET_BLINK_MODE            0x02
#define KG_PACKET_ID_CMD_FEEDBACK_GET_PIEZO_MODE            0x03
#define KG_PACKET_ID_CMD_FEEDBACK_SET_PIEZO_MODE            0x04
#define KG_PACKET_ID_CMD_FEEDBACK_GET_VIBRATE_MODE          0x05
#define KG_PACKET_ID_CMD_FEEDBACK_SET_VIBRATE_MODE          0x06
#define KG_PACKET_ID_CMD_FEEDBACK_GET_RGB_MODE              0x07
#define KG_PACKET_ID_CMD_FEEDBACK_SET_RGB_MODE              0x08
// -- command/event split --
#define KG_PACKET_ID_EVT_FEEDBACK_BLINK_MODE                0x01
#define KG_PACKET_ID_EVT_FEEDBACK_PIEZO_MODE                0x02
#define KG_PACKET_ID_EVT_FEEDBACK_VIBRATE_MODE              0x03
#define KG_PACKET_ID_EVT_FEEDBACK_RGB_MODE                  0x04

/* ================================ */
/* KGAPI COMMAND/EVENT DECLARATIONS */
/* ================================ */

/* 0x01 */ uint16_t kg_cmd_feedback_get_blink_mode(uint8_t *mode);
/* 0x02 */ uint16_t kg_cmd_feedback_set_blink_mode(uint8_t mode);
/* 0x03 */ uint16_t kg_cmd_feedback_get_piezo_mode(uint8_t index, uint8_t *mode, uint8_t *duration, uint16_t *frequency);
/* 0x04 */ uint16_t kg_cmd_feedback_set_piezo_mode(uint8_t index, uint8_t mode, uint8_t duration, uint16_t frequency);
/* 0x05 */ uint16_t kg_cmd_feedback_get_vibrate_mode(uint8_t index, uint8_t *mode, uint8_t *duration);
/* 0x06 */ uint16_t kg_cmd_feedback_set_vibrate_mode(uint8_t index, uint8_t mode, uint8_t duration);
/* 0x07 */ uint16_t kg_cmd_feedback_get_rgb_mode(uint8_t index, uint8_t *mode_red, uint8_t *mode_green, uint8_t *mode_blue);
/* 0x08 */ uint16_t kg_cmd_feedback_set_rgb_mode(uint8_t index, uint8_t mode_red, uint8_t mode_green, uint8_t mode_blue);
// -- command/event split --
/* 0x01 */ extern uint8_t (*kg_evt_feedback_blink_mode)(uint8_t mode);
/* 0x02 */ extern uint8_t (*kg_evt_feedback_piezo_mode)(uint8_t index, uint8_t mode, uint8_t duration, uint16_t frequency);
/* 0x03 */ extern uint8_t (*kg_evt_feedback_vibrate_mode)(uint8_t index, uint8_t mode, uint8_t duration);
/* 0x04 */ extern uint8_t (*kg_evt_feedback_rgb_mode)(uint8_t index, uint8_t mode_red, uint8_t mode_green, uint8_t mode_blue);

uint8_t process_protocol_command_feedback(uint8_t *rxPacket);

#endif // _SUPPORT_PROTOCOL_FEEDBACK_H_
