Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/application.cpp File Reference
application.cpp File Reference
USER-DEFINED: Custom application behavior definition
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_feedback.h"
#include "support_motion.h"
#include "support_touch.h"
#include "support_bluetooth.h"
#include "support_hid_keyboard.h"
#include "application.h"
Functions
uint8_t my_kg_evt_system_ready ()
Indicates that Keyglove has completed the boot process.
uint8_t my_kg_evt_system_timer_tick (uint8_t handle, uint32_t seconds, uint8_t subticks)
Indicates that a previously scheduled software timer has elapsed.
uint8_t my_kg_evt_motion_data (uint8_t index, uint8_t flags, uint8_t data_len, uint8_t *data_data)
Indicates that a motion sensor's measurement data has been updated.
uint8_t my_kg_evt_bluetooth_ready ()
"bluetooth_ready" event handler
uint8_t my_kg_evt_touch_status (uint8_t status_len, uint8_t *status_data)
Indicates that the touch sensor status has changed.
void setup_application ()
Custom application setup routine.
Variables
uint8_t touch_data_prev [4]
Container for tracking previous touch status bits.
uint8_t touch_data_xor [4]
Container for XOR'd touch status bits.
Detailed Description
USER-DEFINED: Custom application behavior definition
Author
Jeff Rowberg
Date
2014-11-07
Use this file to define any autonomous behavior the firmware should have. By default, the processor will boot into what would be considered "idle" mode, available for KGAPI control from an external host but otherwise not really doing anything. Using custom event handlers, you can trigger actions based on API events, such as boot/reset, Bluetooth ready, touch status changing, etc.
Technically these custom event handlers could go anywhere in the codebase, but it makes sense to centralize everything in one place for simplicity. You will most likely not need to modify any other source files (except possibly the "config.h" file which defines the modular hardware configuration), unless you are intentionally changing or adding to the low-level functionality of the Keyglove codebase.
Definition in file application.cpp.
Function Documentation
uint8_t my_kg_evt_bluetooth_ready ()
"bluetooth_ready" event handler
Returns
KGAPI event packet fallthrough, zero allows and non-zero prevents
This event is triggered once the Bluetooth subsystem has been tested for the expected communication response over UART, and all relevant module settings have been requested and parsed.
Definition at line 127 of file application.cpp.
Referenced by setup_application().
uint8_t my_kg_evt_motion_data (uint8_t index, uint8_t flags, uint8_t data_len, uint8_t * data_data)
Indicates that a motion sensor's measurement data has been updated.
Parameters
[in] index Relevant motion sensor
[in] flags Flags indicating which measurement data is represented
[in] data_len Length in bytes of data_data buffer
[in] data_data New measurement data
Returns
KGAPI event packet fallthrough, zero allows and non-zero prevents
Definition at line 111 of file application.cpp.
Referenced by setup_application().
uint8_t my_kg_evt_system_ready ()
Indicates that Keyglove has completed the boot process.
Returns
KGAPI event packet fallthrough, zero allows and non-zero prevents
This event is triggered on every power-on or reset, after all internal subsystems have been initialized. For custom application behavior, it is similar to a "main()" entry point in C, or the "setup()" function in an Arduino sketch. Note that the "system_boot" event may seem intuitive for this purpose also, but that runs before the individual subsystem setup functions, which may overwrite some settings (like feedback mode changes).
Definition at line 72 of file application.cpp.
Referenced by setup_application().
uint8_t my_kg_evt_system_timer_tick (uint8_t handle, uint32_t seconds, uint8_t subticks)
Indicates that a previously scheduled software timer has elapsed.
Parameters
[in] handle Timer handle which triggered this event
[in] seconds Seconds elapsed since boot
[in] subticks 10ms subticks above whole second
Returns
KGAPI event packet fallthrough, zero allows and non-zero prevents
Definition at line 93 of file application.cpp.
Referenced by setup_application().
uint8_t my_kg_evt_touch_status (uint8_t status_len, uint8_t * status_data)
Indicates that the touch sensor status has changed.
Parameters
[in] status_len Length in bytes of status_data buffer
[in] status_data New touch status
Returns
KGAPI event packet fallthrough, zero allows and non-zero prevents
This event is triggered every time any touch status bits change. This data is detected in the update_board_touch() function in the board definition file, and filtered/debounced in the update_touch() function in the support_touch.h file.
Definition at line 146 of file application.cpp.
Referenced by setup_application().
void setup_application ()
Custom application setup routine.
This function is called during the main firmware initialization procedure, inside the setup() function in the keyglove.ino file. It is necessary here to assign the event handler functions to the correct function pointers; without this step, the handlers defined above will not be called when the relevant events are generated.
You can also place any other application initialization code in this function to ensure that it is run anytime the system boots or is reset.
Definition at line 187 of file application.cpp.
Referenced by setup().