Keyglove: BTKeyboardWrapper Class Reference
BTKeyboardWrapper Class Reference
Simple wrapper for Teensy-like keyboard behavior and iWRAP raw HID report interface.
#include <support_bluetooth2_iwrap.h>
Public Member Functions
void set_key1 (uint8_t code)
Set the key code for keyboard report position 1 of 6.
void set_key2 (uint8_t code)
Set the key code for keyboard report position 2 of 6.
void set_key3 (uint8_t code)
Set the key code for keyboard report position 3 of 6.
void set_key4 (uint8_t code)
Set the key code for keyboard report position 4 of 6.
void set_key5 (uint8_t code)
Set the key code for keyboard report position 5 of 6.
void set_key6 (uint8_t code)
Set the key code for keyboard report position 6 of 6.
void set_modifier (uint8_t code)
Set the modifier key bitmask in the keyboard report.
void send_now ()
Send the HID report using current data.
Detailed Description
Simple wrapper for Teensy-like keyboard behavior and iWRAP raw HID report interface.
Definition at line 106 of file support_bluetooth2_iwrap.h.
Member Function Documentation
void BTKeyboardWrapper::set_key1 (uint8_t code)
Set the key code for keyboard report position 1 of 6.
Parameters
[in] code Key code to use
Definition at line 148 of file support_bluetooth2_iwrap.cpp.
Referenced by keyboard_key_down(), and keyboard_key_up().
void BTKeyboardWrapper::set_key2 (uint8_t code)
Set the key code for keyboard report position 2 of 6.
Parameters
[in] code Key code to use
Definition at line 153 of file support_bluetooth2_iwrap.cpp.
Referenced by keyboard_key_down(), and keyboard_key_up().
void BTKeyboardWrapper::set_key3 (uint8_t code)
Set the key code for keyboard report position 3 of 6.
Parameters
[in] code Key code to use
Definition at line 158 of file support_bluetooth2_iwrap.cpp.
Referenced by keyboard_key_down(), and keyboard_key_up().
void BTKeyboardWrapper::set_key4 (uint8_t code)
Set the key code for keyboard report position 4 of 6.
Parameters
[in] code Key code to use
Definition at line 163 of file support_bluetooth2_iwrap.cpp.
Referenced by keyboard_key_down(), and keyboard_key_up().
void BTKeyboardWrapper::set_key5 (uint8_t code)
Set the key code for keyboard report position 5 of 6.
Parameters
[in] code Key code to use
Definition at line 168 of file support_bluetooth2_iwrap.cpp.
Referenced by keyboard_key_down(), and keyboard_key_up().
void BTKeyboardWrapper::set_key6 (uint8_t code)
Set the key code for keyboard report position 6 of 6.
Parameters
[in] code Key code to use
Definition at line 173 of file support_bluetooth2_iwrap.cpp.
Referenced by keyboard_key_down(), and keyboard_key_up().
void BTKeyboardWrapper::set_modifier (uint8_t code)
Set the modifier key bitmask in the keyboard report.
Parameters
[in] code Key code to use
Definition at line 178 of file support_bluetooth2_iwrap.cpp.
Referenced by keyboard_modifier_down(), and keyboard_modifier_up().
The documentation for this class was generated from the following files:
C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_bluetooth2_iwrap.h
C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_bluetooth2_iwrap.cpp