Keyglove: BTMouseWrapper Class Reference
BTMouseWrapper Class Reference
Simple wrapper for Teensy-like mouse behavior and iWRAP HID interface.
#include <support_bluetooth2_iwrap.h>
Public Member Functions
void move (int8_t x, int8_t y)
Move the mouse cursor some relative amount.
void scroll (int8_t vscroll, int8_t hscroll)
Scroll on either axis.
void move (int8_t x, int8_t y, int8_t vscroll, int8_t hscroll)
Move the mouse cursor and/or scroll on either axis.
Detailed Description
Simple wrapper for Teensy-like mouse behavior and iWRAP HID interface.
Definition at line 122 of file support_bluetooth2_iwrap.h.
Member Function Documentation
void BTMouseWrapper::move (int8_t x, int8_t y)
Move the mouse cursor some relative amount.
Parameters
[in] x Pixels to move cursor horizontally (positive=right)
[in] y Pixels to move cursor vertically (positive=down)
Definition at line 194 of file support_bluetooth2_iwrap.cpp.
Referenced by scroll(), and update_hid_mouse().
void BTMouseWrapper::move (int8_t x, int8_t y, int8_t vscroll, int8_t hscroll)
Move the mouse cursor and/or scroll on either axis.
Parameters
[in] x Pixels to move cursor horizontally (positive=right)
[in] y Pixels to move cursor vertically (positive=down)
[in] vscroll Lines to move vertically (positive=down)
[in] hscroll Characters to move horizontally (positive=right)
Definition at line 212 of file support_bluetooth2_iwrap.cpp.
void BTMouseWrapper::scroll (int8_t vscroll, int8_t hscroll)
Scroll on either axis.
Parameters
[in] vscroll Lines to move vertically (positive=down)
[in] hscroll Characters to move horizontally (positive=right)
Definition at line 202 of file support_bluetooth2_iwrap.cpp.
Referenced by update_hid_mouse().
The documentation for this class was generated from the following files:
C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_bluetooth2_iwrap.h
C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_bluetooth2_iwrap.cpp