Keyglove: Quaternion Class Reference
Quaternion Class Reference
Provides float-based quaternion representation and manipulation.
#include <support_helper_3dmath.h>
Public Member Functions
Quaternion ()
Initializes quaternion to known "zero" state.
Quaternion (float nw, float nx, float ny, float nz)
Initializes quaternion with provided components.
Quaternion getProduct (Quaternion q)
Calculate the product of two quaternions Q1 * Q2.
Quaternion getConjugate ()
Calculate the conjugate of this quaternion.
float getMagnitude ()
Calculate the magnitude of this quaternion.
void normalize ()
Normalize this quaternion (scales so magnitude = 1.0)
Quaternion getNormalized ()
Create normalized copy of this quaternion.
Data Fields
float w
Vector rotation component of quaternion.
float x
X-axis rotation component of quaternion.
float y
Y-axis rotation component of quaternion.
float z
Z-axis rotation component of quaternion.
Detailed Description
Provides float-based quaternion representation and manipulation.
Definition at line 41 of file support_helper_3dmath.h.
Constructor & Destructor Documentation
Quaternion::Quaternion (float nw, float nx, float ny, float nz)
Initializes quaternion with provided components.
Parameters
[in] nw W element
[in] nx X element
[in] ny Y element
[in] nz Z element
Definition at line 60 of file support_helper_3dmath.cpp.
Member Function Documentation
Quaternion Quaternion::getConjugate ()
Calculate the conjugate of this quaternion.
Returns
Calculated quaternion conjugate
Definition at line 89 of file support_helper_3dmath.cpp.
float Quaternion::getMagnitude ()
Calculate the magnitude of this quaternion.
Returns
Calculated quaternion magnitude
Definition at line 97 of file support_helper_3dmath.cpp.
Referenced by normalize().
Quaternion Quaternion::getNormalized ()
Create normalized copy of this quaternion.
Returns
Normalized quaternion
Definition at line 116 of file support_helper_3dmath.cpp.
Quaternion Quaternion::getProduct (Quaternion q)
Calculate the product of two quaternions Q1 * Q2.
Parameters
[in] q Second quaternion (Q2) in calculation
Returns
Calculated quaternion product
Definition at line 72 of file support_helper_3dmath.cpp.
Referenced by VectorInt16::rotate(), and VectorFloat::rotate().
The documentation for this class was generated from the following files:
C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_helper_3dmath.h
C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_helper_3dmath.cpp