Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/custom_protocol.cpp File Reference
custom_protocol.cpp File Reference
USER-DEFINED: Custom protocol filtering implementations
#include "keyglove.h"
#include "support_protocol.h"
Functions
uint8_t filter_incoming_keyglove_packet (uint8_t *rxPacket)
Custom filter for incoming command packets.
uint8_t filter_outgoing_keyglove_packet (uint8_t *packetType, uint8_t *payloadLength, uint8_t *packetClass, uint8_t *packetId, uint8_t *payload)
Custom filter for outgoing response/event packets.
uint8_t process_protocol_command_custom (uint8_t *rxPacket)
Custom command identification and execution.
Detailed Description
USER-DEFINED: Custom protocol filtering implementations
Author
Jeff Rowberg
Date
2014-11-07
This file can be used to alter the behavior of predefined API packets without actually modifying the portions of code where those packets are defined. It can also be used to add support for new KGAPI commands which you may want for your custom functionality.
Definition in file custom_protocol.cpp.
Function Documentation
uint8_t filter_incoming_keyglove_packet (uint8_t * rxPacket)
Custom filter for incoming command packets.
Parameters
[in,out] rxPacket Incoming packet byte array (guaranteed to be well-formed)
Returns
KGAPI command packet fallthrough, zero allows and non-zero prevents
This function should not be used to add support for new commands; it is only for filtering/modifying packets on-the-fly if desired. To add new commands, refer to the process_protocol_command_custom() function instead.
See also
protocol_parse()
process_protocol_command_custom()
Definition at line 55 of file custom_protocol.cpp.
Referenced by protocol_parse().
uint8_t filter_outgoing_keyglove_packet (uint8_t * packetType, uint8_t * payloadLength, uint8_t * packetClass, uint8_t * packetId, uint8_t * payload)
Custom filter for outgoing response/event packets.
Parameters
[in,out] packetType Packet type (0x80 = event, 0xC0 = response)
[in,out] payloadLength Length of packet payload data
[in,out] packetClass Packet class byte
[in,out] packetId Packet ID byte
[in,out] payload Packet payload data (may be 0 if payloadLength is 0)
Returns
KGAPI response/event packet fallthrough, zero allows and non-zero prevents
Definition at line 78 of file custom_protocol.cpp.
Referenced by send_keyglove_packet().
uint8_t process_protocol_command_custom (uint8_t * rxPacket)
Custom command identification and execution.
Parameters
[in] rxPacket Incoming command packet byte array (guaranteed to be well-formed)
Returns
KGAPI protocol error code after parsing/detecting command data
See also
protocol_parse()
Definition at line 98 of file custom_protocol.cpp.
Referenced by protocol_parse().