Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/keyglove.cpp File Reference
keyglove.cpp File Reference
Main setup/loop controller implementations.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_touch.h"
#include "support_feedback.h"
#include "support_motion.h"
#include "support_bluetooth.h"
#include "support_hid_keyboard.h"
#include "support_hid_mouse.h"
#include "application.h"
Functions
void setup ()
Microcontroller initial setup routine.
void loop ()
Microcontroller infinite loop routine.
uint16_t kg_cmd_system_ping (uint32_t *runtime)
Test communication with Keyglove device and get current runtime.
uint16_t kg_cmd_system_reset (uint8_t type)
Reset Keyglove device.
uint16_t kg_cmd_system_get_info (uint8_t *major, uint8_t *minor, uint8_t *patch, uint32_t *timestamp)
Get firmware build info.
uint16_t kg_cmd_system_get_memory (uint32_t *free_ram, uint32_t *total_ram)
Get system memory usage.
uint16_t kg_cmd_system_set_timer (uint8_t handle, uint16_t interval, uint8_t oneshot)
Set a timer interval to trigger future behavior.
uint16_t kg_cmd_system_get_battery_status (uint8_t *status, uint8_t *level)
Get battery status.
Variables
volatile uint8_t keyglove100Hz = 0
Flag for 100Hz hardware timer interrupt.
uint8_t keygloveTick = 0
Fast 100Hz counter, increments every ~10ms and loops at 100.
uint32_t keygloveTock = 0
Slow 1Hz counter (a.k.a. "uptime"), increments every 100 ticks and loops at 2^32 (~4 billion)
uint8_t keygloveSoftTimers = 0
Bitmask for defined scheduled timers (one-shot or repeating)
uint8_t keygloveSoftTimersRepeat = 0
Bitmask for which scheduled timers are repeating.
uint16_t keygloveSoftTimerInterval [8]
Interval for each defined timer (units are 10ms)
uint32_t keygloveSoftTimerSec [8]
Next "second" (tock) to execute each timer.
uint8_t keygloveSoftTimer10ms [8]
Next 10ms (tick) to execute each timer (w/corresponding second)
volatile uint8_t keygloveBatteryInterrupt
Flag for battery status change interrupt.
volatile uint8_t keygloveBatteryStatus
Battery status signal container for post-interrupt processing.
uint8_t keygloveBatteryLevel
Battery charge level (0-100)
Detailed Description
Main setup/loop controller implementations.
Author
Jeff Rowberg
Date
2014-11-07
This is the main entry point and program flow control code for the entire Keyglove Arduino firmware project, including the setup() and loop() functions.
Normally it is not necessary to edit this file.
Definition in file keyglove.cpp.
Function Documentation
uint16_t kg_cmd_system_get_battery_status (uint8_t * status, uint8_t * level)
Get battery status.
Parameters
[out] status Battery status
[out] level Charge level (0-100)
Returns
Result code (0=success)
Definition at line 425 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_get_info (uint8_t * major, uint8_t * minor, uint8_t * patch, uint32_t * timestamp)
Get firmware build info.
Parameters
[out] major Firmware major version number
[out] minor Firmware minor version number
[out] patch Firmware patch version number
[out] timestamp Firmware build timestamp
Returns
Result code (0=success)
Definition at line 366 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_get_memory (uint32_t * free_ram, uint32_t * total_ram)
Get system memory usage.
Parameters
[out] free_ram Free RAM
[out] total_ram Total RAM
Returns
Result code (0=success)
Definition at line 380 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_ping (uint32_t * runtime)
Test communication with Keyglove device and get current runtime.
Parameters
[out] runtime Number of seconds since last boot/reset
Returns
Result code (0=success)
Definition at line 328 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_reset (uint8_t type)
Reset Keyglove device.
Parameters
[in] type Type of reset to perform
Returns
Result code (0=success)
Definition at line 338 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_set_timer (uint8_t handle, uint16_t interval, uint8_t oneshot)
Set a timer interval to trigger future behavior.
Parameters
[in] handle Timer handle (0-7)
[in] interval Interval (10ms units)
[in] oneshot Repeating (0) or one-shot (1)
Returns
Result code (0=success)
Definition at line 396 of file keyglove.cpp.
Referenced by process_protocol_command_system().
void loop ()
Microcontroller infinite loop routine.
This routine loops forever while the microcontroller is running. It is responsible for checking on touch status, motion sensor status, and generally everything else which does not rely strictly on hardware interrupts to operate. Even some interrupt-related code is found here, since the interrupt handlers typically just set a flag which causes this code to process the event, so that the actual longer-running execution does not block any other interrupts from occuring.
Definition at line 189 of file keyglove.cpp.
void setup ()
Microcontroller initial setup routine.
Runs on power-on or reset, and again if system_reset BGAPI command is received.
Definition at line 101 of file keyglove.cpp.
Referenced by kg_cmd_system_reset().