Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_protocol_bluetooth.h File Reference
support_protocol_bluetooth.h File Reference
KGAPI "bluetooth" protocol command parser declarations.
Macros
#define KG_PACKET_ID_CMD_BLUETOOTH_GET_MODE 0x01
#define KG_PACKET_ID_CMD_BLUETOOTH_SET_MODE 0x02
#define KG_PACKET_ID_CMD_BLUETOOTH_RESET 0x03
#define KG_PACKET_ID_CMD_BLUETOOTH_GET_MAC 0x04
#define KG_PACKET_ID_CMD_BLUETOOTH_GET_PAIRINGS 0x05
#define KG_PACKET_ID_CMD_BLUETOOTH_DISCOVER 0x06
#define KG_PACKET_ID_CMD_BLUETOOTH_PAIR 0x07
#define KG_PACKET_ID_CMD_BLUETOOTH_DELETE_PAIRING 0x08
#define KG_PACKET_ID_CMD_BLUETOOTH_CLEAR_PAIRINGS 0x09
#define KG_PACKET_ID_CMD_BLUETOOTH_GET_CONNECTIONS 0x0A
#define KG_PACKET_ID_CMD_BLUETOOTH_CONNECT 0x0B
#define KG_PACKET_ID_CMD_BLUETOOTH_DISCONNECT 0x0C
#define KG_PACKET_ID_EVT_BLUETOOTH_MODE 0x01
#define KG_PACKET_ID_EVT_BLUETOOTH_READY 0x02
#define KG_PACKET_ID_EVT_BLUETOOTH_INQUIRY_RESPONSE 0x03
#define KG_PACKET_ID_EVT_BLUETOOTH_INQUIRY_COMPLETE 0x04
#define KG_PACKET_ID_EVT_BLUETOOTH_PAIRING_STATUS 0x05
#define KG_PACKET_ID_EVT_BLUETOOTH_PAIRING_FAILED 0x06
#define KG_PACKET_ID_EVT_BLUETOOTH_PAIRINGS_CLEARED 0x07
#define KG_PACKET_ID_EVT_BLUETOOTH_CONNECTION_STATUS 0x08
#define KG_PACKET_ID_EVT_BLUETOOTH_CONNECTION_CLOSED 0x09
Functions
uint16_t kg_cmd_bluetooth_get_mode (uint8_t *mode)
Get current mode for Bluetooth subsystem.
uint16_t kg_cmd_bluetooth_set_mode (uint8_t mode)
Set new mode for Bluetooth subsystem.
uint16_t kg_cmd_bluetooth_reset ()
Reset Bluetooth subsystem.
uint16_t kg_cmd_bluetooth_get_mac (uint8_t *address)
Get local Bluetooth MAC address.
uint16_t kg_cmd_bluetooth_get_pairings (uint8_t *count)
Get a list of all paired devices.
uint16_t kg_cmd_bluetooth_discover (uint8_t duration)
Perform Bluetooth inquiry to locate nearby devices.
uint16_t kg_cmd_bluetooth_pair (uint8_t *address)
Initiate pairing request to remote device.
uint16_t kg_cmd_bluetooth_delete_pairing (uint8_t index)
Remove a specific pairing entry.
uint16_t kg_cmd_bluetooth_clear_pairings ()
Remove all pairing entries.
uint16_t kg_cmd_bluetooth_get_connections (uint8_t *count)
Get a list of all open or pending connections.
uint16_t kg_cmd_bluetooth_connect (uint8_t index, uint8_t profile)
Attempt to open a connection to a specific paired device using a specific profile.
uint16_t kg_cmd_bluetooth_disconnect (uint8_t handle)
Close a specific Bluetooth connection.
uint8_t process_protocol_command_bluetooth (uint8_t *rxPacket)
Command processing routine for "bluetooth" packet class.
Variables
uint8_t(* kg_evt_bluetooth_mode)(uint8_t mode)
uint8_t(* kg_evt_bluetooth_ready)()
uint8_t(* kg_evt_bluetooth_inquiry_response)(uint8_t *address, uint8_t *cod, int8_t rssi, uint8_t status, uint8_t index, uint8_t name_len, uint8_t *name_data)
uint8_t(* kg_evt_bluetooth_inquiry_complete)(uint8_t count)
uint8_t(* kg_evt_bluetooth_pairing_status)(uint8_t index, uint8_t *address, uint8_t priority, uint8_t profiles_supported, uint8_t profiles_active, uint8_t handle_list_len, uint8_t *handle_list_data)
uint8_t(* kg_evt_bluetooth_pairing_failed)(uint8_t *address)
uint8_t(* kg_evt_bluetooth_pairings_cleared)()
uint8_t(* kg_evt_bluetooth_connection_status)(uint8_t handle, uint8_t *address, uint8_t index, uint8_t profile, uint8_t status)
uint8_t(* kg_evt_bluetooth_connection_closed)(uint8_t handle, uint16_t reason)
Detailed Description
KGAPI "bluetooth" protocol command parser declarations.
Author
Jeff Rowberg
Date
2014-11-03
This file implements subsystem-specific command processing functions for the "bluetooth" part of the KGAPI protocol.
Normally it is not necessary to edit this file. (It is also autogenerated.)
Definition in file support_protocol_bluetooth.h.
Function Documentation
uint16_t kg_cmd_bluetooth_clear_pairings ()
Remove all pairing entries.
Returns
Result code (0=success)
Definition at line 1649 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_connect (uint8_t index, uint8_t profile)
Attempt to open a connection to a specific paired device using a specific profile.
Parameters
[in] index Index of pairing to use
[in] profile Profile to use for connection
Returns
Result code (0=success)
Definition at line 1737 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_delete_pairing (uint8_t index)
Remove a specific pairing entry.
Parameters
[in] index Index of pairing to delete
Returns
Result code (0=success)
Definition at line 1610 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_disconnect (uint8_t handle)
Close a specific Bluetooth connection.
Parameters
[in] handle Link ID of connection to close
Returns
Result code (0=success)
Definition at line 1806 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_discover (uint8_t duration)
Perform Bluetooth inquiry to locate nearby devices.
Parameters
[in] duration Number of seconds to run discovery process
Returns
Result code (0=success)
Definition at line 1554 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_connections (uint8_t * count)
Get a list of all open or pending connections.
Parameters
[out] count Number of open or pending connections
Returns
Result code (0=success)
Definition at line 1664 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_mac (uint8_t * address)
Get local Bluetooth MAC address.
Parameters
[out] address Local six-byte Bluetooth MAC address
Returns
Result code (0=success)
Definition at line 1481 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_mode (uint8_t * mode)
Get current mode for Bluetooth subsystem.
Parameters
[out] mode Current Bluetooth mode
Returns
Result code (0=success)
Definition at line 1358 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_pairings (uint8_t * count)
Get a list of all paired devices.
Parameters
[out] count Number of paired devices
Returns
Result code (0=success)
Definition at line 1500 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_pair (uint8_t * address)
Initiate pairing request to remote device.
Parameters
[in] address Six-byte Bluetooth MAC address of remote device to pair with
Returns
Result code (0=success)
Definition at line 1586 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_reset ()
Reset Bluetooth subsystem.
Returns
Result code (0=success)
Definition at line 1463 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth(), and setup().
uint16_t kg_cmd_bluetooth_set_mode (uint8_t mode)
Set new mode for Bluetooth subsystem.
Parameters
[in] mode New Bluetooth mode to set
Returns
Result code (0=success)
Definition at line 1373 of file support_bluetooth2_iwrap.cpp.
Referenced by my_kg_evt_bluetooth_ready(), and process_protocol_command_bluetooth().
uint8_t process_protocol_command_bluetooth (uint8_t * rxPacket)
Command processing routine for "bluetooth" packet class.
Parameters
[in] rxPacket Incoming KGAPI packet buffer
Returns
Protocol error, if any (0 for success)
See also
protocol_parse()
KGAPI command: kg_cmd_bluetooth_get_mode()
KGAPI command: kg_cmd_bluetooth_set_mode()
KGAPI command: kg_cmd_bluetooth_reset()
KGAPI command: kg_cmd_bluetooth_get_mac()
KGAPI command: kg_cmd_bluetooth_get_pairings()
KGAPI command: kg_cmd_bluetooth_discover()
KGAPI command: kg_cmd_bluetooth_pair()
KGAPI command: kg_cmd_bluetooth_delete_pairing()
KGAPI command: kg_cmd_bluetooth_clear_pairings()
KGAPI command: kg_cmd_bluetooth_get_connections()
KGAPI command: kg_cmd_bluetooth_connect()
KGAPI command: kg_cmd_bluetooth_disconnect()
Definition at line 63 of file support_protocol_bluetooth.cpp.
Referenced by protocol_parse().