Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_hid_keyboard.h File Reference
support_hid_keyboard.h File Reference
HID keyboard helper function declarations.
Macros
#define MODIFIERKEY_CTRL 0x04
#define MODIFIERKEY_SHIFT 0x02
#define MODIFIERKEY_ALT 0x01
#define MODIFIERKEY_GUI 0x08
#define KEY_A 4
#define KEY_B 5
#define KEY_C 6
#define KEY_D 7
#define KEY_E 8
#define KEY_F 9
#define KEY_G 10
#define KEY_H 11
#define KEY_I 12
#define KEY_J 13
#define KEY_K 14
#define KEY_L 15
#define KEY_M 16
#define KEY_N 17
#define KEY_O 18
#define KEY_P 19
#define KEY_Q 20
#define KEY_R 21
#define KEY_S 22
#define KEY_T 23
#define KEY_U 24
#define KEY_V 25
#define KEY_W 26
#define KEY_X 27
#define KEY_Y 28
#define KEY_Z 29
#define KEY_1 30
#define KEY_2 31
#define KEY_3 32
#define KEY_4 33
#define KEY_5 34
#define KEY_6 35
#define KEY_7 36
#define KEY_8 37
#define KEY_9 38
#define KEY_0 39
#define KEY_ENTER 40
#define KEY_ESC 41
#define KEY_BACKSPACE 42
#define KEY_TAB 43
#define KEY_SPACE 44
#define KEY_MINUS 45
#define KEY_EQUAL 46
#define KEY_LEFT_BRACE 47
#define KEY_RIGHT_BRACE 48
#define KEY_BACKSLASH 49
#define KEY_NON_US_NUM 50
#define KEY_SEMICOLON 51
#define KEY_QUOTE 52
#define KEY_TILDE 53
#define KEY_COMMA 54
#define KEY_PERIOD 55
#define KEY_SLASH 56
#define KEY_CAPS_LOCK 57
#define KEY_F1 58
#define KEY_F2 59
#define KEY_F3 60
#define KEY_F4 61
#define KEY_F5 62
#define KEY_F6 63
#define KEY_F7 64
#define KEY_F8 65
#define KEY_F9 66
#define KEY_F10 67
#define KEY_F11 68
#define KEY_F12 69
#define KEY_PRINTSCREEN 70
#define KEY_SCROLL_LOCK 71
#define KEY_PAUSE 72
#define KEY_INSERT 73
#define KEY_HOME 74
#define KEY_PAGE_UP 75
#define KEY_DELETE 76
#define KEY_END 77
#define KEY_PAGE_DOWN 78
#define KEY_RIGHT 79
#define KEY_LEFT 80
#define KEY_DOWN 81
#define KEY_UP 82
#define KEY_NUM_LOCK 83
#define KEYPAD_SLASH 84
#define KEYPAD_ASTERIX 85
#define KEYPAD_MINUS 86
#define KEYPAD_PLUS 87
#define KEYPAD_ENTER 88
#define KEYPAD_1 89
#define KEYPAD_2 90
#define KEYPAD_3 91
#define KEYPAD_4 92
#define KEYPAD_5 93
#define KEYPAD_6 94
#define KEYPAD_7 95
#define KEYPAD_8 96
#define KEYPAD_9 97
#define KEYPAD_0 98
#define KEYPAD_PERIOD 99
#define KEYPAD_ASTERISK 85
#define KEY_BACKSLASH2 100
#define KEY_APP 101
#define KEY_POWER 102
#define KEYPAD_EQUAL 103
#define KEY_EXECUTE 116
#define KEY_HELP 117
#define KEY_MENU 118
#define KEY_SELECT 119
#define KEY_STOP 120
#define KEY_AGAIN 121
#define KEY_UNDO 122
#define KEY_CUT 123
#define KEY_COPY 124
#define KEY_PASTE 125
#define KEY_FIND 126
#define KEY_MUTE 127
#define KEY_VOLUP 128
#define KEY_VOLDOWN 129
Functions
void setup_hid_keyboard ()
Initialize HID keyboard behavior.
void keyboard_key_down (uint8_t code)
Send key press (down) HID report.
void keyboard_key_up (uint8_t code)
Send key release (up) HID report.
void keyboard_key_press (uint8_t code)
Send keypress (down-up) HID reports.
void keyboard_modifier_down (uint8_t code)
Send modifier press (down) HID report.
void keyboard_modifier_up (uint8_t code)
Send modifier release (up) HID report.
void keyboard_modifier_toggle (uint8_t code)
Switch modifier state to opposite of what it was (down vs. up)
void keyboard_modifier_press (uint8_t code)
Send modifier keypress (down-up) HID reports.
Variables
uint8_t hidModifiersDown
Modifier keys currently down.
uint8_t hidKeysDown [6]
Normal keys currently down.
Detailed Description
HID keyboard helper function declarations.
Author
Jeff Rowberg
Date
2014-11-07
Definition in file support_hid_keyboard.h.
Function Documentation
void keyboard_key_down (uint8_t code)
Send key press (down) HID report.
Parameters
[in] code Key code
Definition at line 65 of file support_hid_keyboard.cpp.
Referenced by keyboard_key_press(), and my_kg_evt_touch_status().
void keyboard_key_press (uint8_t code)
Send keypress (down-up) HID reports.
Parameters
[in] code Modifier key bitmask
Definition at line 213 of file support_hid_keyboard.cpp.
Referenced by my_kg_evt_touch_status().
void keyboard_key_up (uint8_t code)
Send key release (up) HID report.
Parameters
[in] code Key code
Definition at line 138 of file support_hid_keyboard.cpp.
Referenced by keyboard_key_press(), and my_kg_evt_touch_status().
void keyboard_modifier_down (uint8_t code)
Send modifier press (down) HID report.
Parameters
[in] code Modifier key bitmask
Definition at line 225 of file support_hid_keyboard.cpp.
Referenced by keyboard_modifier_press(), and keyboard_modifier_toggle().
void keyboard_modifier_press (uint8_t code)
Send modifier keypress (down-up) HID reports.
Parameters
[in] code Modifier key bitmask
Definition at line 281 of file support_hid_keyboard.cpp.
void keyboard_modifier_toggle (uint8_t code)
Switch modifier state to opposite of what it was (down vs. up)
Parameters
[in] code Modifier key bitmask
Definition at line 267 of file support_hid_keyboard.cpp.
void keyboard_modifier_up (uint8_t code)
Send modifier release (up) HID report.
Parameters
[in] code Modifier key bitmask
Definition at line 245 of file support_hid_keyboard.cpp.
Referenced by keyboard_modifier_press(), and keyboard_modifier_toggle().