Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_feedback_piezo.cpp File Reference
support_feedback_piezo.cpp File Reference
Feedback implementations for piezo buzzer.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_feedback.h"
Functions
void feedback_set_piezo_tone (uint16_t frequency)
Enables or disables the piezo buzzer using a certain frequency.
void feedback_set_piezo_mode (feedback_piezo_mode_t mode, uint8_t duration, uint16_t frequency)
Sets the operational mode of the piezo buzzer.
void setup_feedback_piezo ()
Initialize piezo feedback subsystem.
void update_feedback_piezo ()
Update status of piezo feedback subystem, called at 100Hz from loop()
uint16_t kg_cmd_feedback_get_piezo_mode (uint8_t index, uint8_t *mode, uint8_t *duration, uint16_t *frequency)
Get current feedback mode for a piezo buzzer.
uint16_t kg_cmd_feedback_set_piezo_mode (uint8_t index, uint8_t mode, uint8_t duration, uint16_t frequency)
Set a new piezo feedback mode for a piezo buzzer.
Variables
feedback_piezo_mode_t feedbackPiezoMode
Piezo sound mode.
uint16_t feedbackPiezoTick
Piezo tick reference.
uint16_t feedbackPiezoDuration
Piezo pattern duration.
uint16_t feedbackPiezoFrequency
Piezo frequency to use for tone generation.
Detailed Description
Feedback implementations for piezo buzzer.
Author
Jeff Rowberg
Date
2014-11-07
This file defines the feeback functionality for the piezo buzzer that may be included as an optional module in a Keyglove modular hardware design. This file is meant to contain only behavioral logic and abstracted functions that do not require specific pin knowledge of the selected MCU. Any pins used should be defined in the selected MCU board support file.
Normally it is not necessary to edit this file.
Definition in file support_feedback_piezo.cpp.
Function Documentation
void feedback_set_piezo_mode (feedback_piezo_mode_t mode, uint8_t duration, uint16_t frequency)
Sets the operational mode of the piezo buzzer.
Parameters
[in] mode Piezo mode to use
[in] duration Duration in 10ms units to run pattern before ending (0 to run forever)
[in] frequency Frequency (Hz) of tone to generate
Definition at line 73 of file support_feedback_piezo.cpp.
Referenced by kg_cmd_feedback_set_piezo_mode(), and update_feedback_piezo().
void feedback_set_piezo_tone (uint16_t frequency)
Enables or disables the piezo buzzer using a certain frequency.
Parameters
[in] frequency Frequency (Hz) of tone to generate, or zero to disable
See also
KG_PIN_PIEZO
Definition at line 59 of file support_feedback_piezo.cpp.
Referenced by feedback_set_piezo_mode(), and update_feedback_piezo().
uint16_t kg_cmd_feedback_get_piezo_mode (uint8_t index, uint8_t * mode, uint8_t * duration, uint16_t * frequency)
Get current feedback mode for a piezo buzzer.
Parameters
[in] index Index of piezo device for which to get the current mode
[out] mode Current feedback mode for specified piezo device
[out] duration Duration to maintain tone
[out] frequency Frequency of tone to generate
Returns
Result code (0=success)
Definition at line 121 of file support_feedback_piezo.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_piezo_mode (uint8_t index, uint8_t mode, uint8_t duration, uint16_t frequency)
Set a new piezo feedback mode for a piezo buzzer.
Parameters
[in] index Index of piezo device for which to set a new mode
[in] mode New feedback mode to set for specified piezo device
[in] duration Duration to maintain tone
[in] frequency Frequency of tone to generate
Returns
Result code (0=success)
Definition at line 137 of file support_feedback_piezo.cpp.
Referenced by process_protocol_command_feedback().