Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_feedback_rgb.cpp File Reference
support_feedback_rgb.cpp File Reference
Feedback implementations for RGB LED.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_feedback.h"
Functions
void feedback_set_rgb_digital (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin digital logic states (red/green/blue)
void feedback_set_rgb_digital_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin digital logic state on one channel (red/green/blue)
void feedback_set_rgb_analog (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin analog PWM states (red/green/blue)
void feedback_set_rgb_analog_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin analog PWM state on one channel (red/green/blue)
void feedback_set_rgb_mode (feedback_rgb_mode_t r, feedback_rgb_mode_t g, feedback_rgb_mode_t b)
Sets RGB feedback modes (red/green/blue)
void setup_feedback_rgb ()
Initialize RGB feedback subsystem.
void update_feedback_rgb ()
Update status of RGB feedback subystem, called at 100Hz from loop()
uint16_t kg_cmd_feedback_get_rgb_mode (uint8_t index, uint8_t *mode_red, uint8_t *mode_green, uint8_t *mode_blue)
Get current feedback mode for an RGB LED.
uint16_t kg_cmd_feedback_set_rgb_mode (uint8_t index, uint8_t mode_red, uint8_t mode_green, uint8_t mode_blue)
Set a new RGB LED feedback mode.
Variables
feedback_rgb_mode_t feedbackRGBMode [3]
RGB feedback red component mode.
int16_t feedbackRGBTick [3]
RGB fade tick reference (signed because of abs equations)
uint16_t feedbackRGBLoop [3]
Tick loop length for RGB fade timing.
Detailed Description
Feedback implementations for RGB LED.
Author
Jeff Rowberg
Date
2014-11-07
This file defines the feeback functionality for the RGB LED that may be included as an optional module in a Keyglove modular hardware design. This file is meant to contain only behavioral logic and abstracted functions that do not require specific pin knowledge of the selected MCU. Any pins used should be defined in the selected MCU board support file.
Normally it is not necessary to edit this file.
Definition in file support_feedback_rgb.cpp.
Function Documentation
void feedback_set_rgb_analog (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin analog PWM states (red/green/blue)
Parameters
[in] r Red: zero for off, non-zero for PWM (on), 255 for no change
[in] g Green: zero for off, non-zero for PWM (on), 255 for no change
[in] b Blue: zero for off, non-zero for PWM (on), 255 for no change
Definition at line 82 of file support_feedback_rgb.cpp.
void feedback_set_rgb_analog_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin analog PWM state on one channel (red/green/blue)
Parameters
[in] channel Channel number (0=RED, 1=GREEN, 2=BLUE)
[in] value PWM duty cycle (zero for off, non-zero for PWM/on)
Definition at line 93 of file support_feedback_rgb.cpp.
Referenced by update_feedback_rgb().
void feedback_set_rgb_digital (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin digital logic states (red/green/blue)
Parameters
[in] r Red: zero for low (off), non-zero for high (on), 255 for no change
[in] g Green: zero for low (off), non-zero for high (on), 255 for no change
[in] b Blue: zero for low (off), non-zero for high (on), 255 for no change
Definition at line 59 of file support_feedback_rgb.cpp.
Referenced by feedback_set_rgb_mode().
void feedback_set_rgb_digital_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin digital logic state on one channel (red/green/blue)
Parameters
[in] channel Channel number (0=RED, 1=GREEN, 2=BLUE)
[in] value Logic state (zero for low/off, non-zero for high/on)
Definition at line 70 of file support_feedback_rgb.cpp.
Referenced by update_feedback_rgb().
void feedback_set_rgb_mode (feedback_rgb_mode_t r, feedback_rgb_mode_t g, feedback_rgb_mode_t b)
Sets RGB feedback modes (red/green/blue)
Parameters
[in] r Red mode
[in] g Green mode
[in] b Blue mode
Definition at line 105 of file support_feedback_rgb.cpp.
Referenced by kg_cmd_feedback_set_rgb_mode().
uint16_t kg_cmd_feedback_get_rgb_mode (uint8_t index, uint8_t * mode_red, uint8_t * mode_green, uint8_t * mode_blue)
Get current feedback mode for an RGB LED.
Parameters
[in] index Index of RGB device for which to get the current mode
[out] mode_red Current feedback mode for specified RGB device red LED
[out] mode_green Current feedback mode for specified RGB device green LED
[out] mode_blue Current feedback mode for specified RGB device blue LED
Returns
Result code (0=success)
Definition at line 212 of file support_feedback_rgb.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_rgb_mode (uint8_t index, uint8_t mode_red, uint8_t mode_green, uint8_t mode_blue)
Set a new RGB LED feedback mode.
Parameters
[in] index Index of RGB device for which to set a new mode
[in] mode_red New feedback mode to set for specified RGB device red LED
[in] mode_green New feedback mode to set for specified RGB device green LED
[in] mode_blue New feedback mode to set for specified RGB device blue LED
Returns
Result code (0=success)
Definition at line 228 of file support_feedback_rgb.cpp.
Referenced by process_protocol_command_feedback().