Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_feedback_blink.cpp File Reference
support_feedback_blink.cpp File Reference
Feedback implementations for single LED.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_feedback.h"
Functions
void feedback_set_blink_logic (uint8_t logic)
Sets LED feedpack pin logic state.
void feedback_set_blink_mode (feedback_blink_mode_t mode)
Sets LED feedback mode.
void setup_feedback_blink ()
Initialize LED feedback subsystem.
void update_feedback_blink ()
Update status of LED feedback subystem, called at 100Hz from loop()
uint16_t kg_cmd_feedback_get_blink_mode (uint8_t *mode)
Get current blink feedback mode.
uint16_t kg_cmd_feedback_set_blink_mode (uint8_t mode)
Set new blink feedback mode.
Variables
feedback_blink_mode_t feedbackBlinkMode
LED blink mode.
uint8_t feedbackBlinkTick
LED blink tick reference.
uint8_t feedbackBlinkLoop
Tick loop length for LED blink timing.
Detailed Description
Feedback implementations for single LED.
Author
Jeff Rowberg
Date
2014-11-07
This file defines the feeback functionality for the blinking LED that is built into many microcontroller boards, e.g. the Teensy++. This file is meant to contain only behavioral logic and abstracted functions that do not require specific pin knowledge of the selected MCU. Any pins used should be defined in the selected MCU board support file.
Normally it is not necessary to edit this file.
Definition in file support_feedback_blink.cpp.
Function Documentation
void feedback_set_blink_logic (uint8_t logic)
Sets LED feedpack pin logic state.
Parameters
[in] logic Zero for low (off), non-zero for high (on)
See also
KG_PIN_BLINK
Definition at line 58 of file support_feedback_blink.cpp.
Referenced by feedback_set_blink_mode(), and update_feedback_blink().
void feedback_set_blink_mode (feedback_blink_mode_t mode)
Sets LED feedback mode.
Parameters
[in] mode New LED mode to set
Definition at line 67 of file support_feedback_blink.cpp.
Referenced by kg_cmd_feedback_set_blink_mode().
uint16_t kg_cmd_feedback_get_blink_mode (uint8_t * mode)
Get current blink feedback mode.
Parameters
[out] mode Current blink feedback mode
Returns
Result code (0=success)
Definition at line 141 of file support_feedback_blink.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_blink_mode (uint8_t mode)
Set new blink feedback mode.
Parameters
[in] mode New blink feedback mode to set
Returns
Result code (0=success)
Definition at line 151 of file support_feedback_blink.cpp.
Referenced by my_kg_evt_system_ready(), and process_protocol_command_feedback().