Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_bluetooth2_iwrap.h File Reference
support_bluetooth2_iwrap.h File Reference
Declarations for Bluetooth using Bluegiga's WT12 module and iWRAP.
#include <iWRAP.h>
Data Structures
struct iwrap_pairing_t
iWRAP paired device record structure
class BTKeyboardWrapper
Simple wrapper for Teensy-like keyboard behavior and iWRAP raw HID report interface.
class BTMouseWrapper
Simple wrapper for Teensy-like mouse behavior and iWRAP HID interface.
Macros
#define KG_BLUETOOTH_ERROR_INTERFACE_NOT_READY 0x0801
Bluetooth interface has not been initialized.
#define KG_BLUETOOTH_ERROR_INTERFACE_BUSY 0x0802
Bluetooth module is currently busy and cannot accept this command.
#define BLUETOOTH_PROFILE_MASK_HID_CONTROL 0x01
Bitmask indicating HID control link.
#define BLUETOOTH_PROFILE_MASK_HID_INTERRUPT 0x02
Bitmask indicating HID interrupt link.
#define BLUETOOTH_PROFILE_MASK_IAP 0x04
Bitmask indicating IAP link.
#define BLUETOOTH_PROFILE_MASK_SPP 0x08
Bitmask indicating SPP (RFCOMM) link.
#define BLUETOOTH_PROFILE_MASK_HFP 0x10
Bitmask indicating HFP link.
#define BLUETOOTH_PROFILE_MASK_AVRCP 0x20
Bitmask indicating AVRCP link.
#define BT2_RAWHID_RX_SIZE 16
Raw HID input payload size.
#define BT2_RAWHID_TX_SIZE 16
Raw HID output payload size.
#define IWRAP_STATE_IDLE 0
iWRAP is idle (known state)
#define IWRAP_STATE_UNKNOWN 1
iWRAP state unknown (e.g. fresh boot)
#define IWRAP_STATE_PENDING_AT 2
iWRAP "AT" communication test pending
#define IWRAP_STATE_PENDING_SET 3
iWRAP settings dump request pending
#define IWRAP_STATE_PENDING_LIST 4
iWRAP connection list request pending
#define IWRAP_STATE_PENDING_CALL 5
iWRAP outgoing call pending
#define IWRAP_STATE_PENDING_INQUIRY 6
iWRAP device inquiry pending
#define IWRAP_STATE_PENDING_PAIR 7
iWRAP outgoing pair attempt pending
#define IWRAP_STATE_PENDING_SETBTPAIR 8
iWRAP pairing entry removal pending
#define IWRAP_STATE_COMM_FAILED 255
iWRAP communication attempted and failed (unusable)
#define IWRAP_MAX_PAIRINGS 16
Maximum pairing entries allowed in iWRAP.
Enumerations
enum bluetooth_mode_t {
KG_BLUETOOTH_MODE_DISABLED = 0, KG_BLUETOOTH_MODE_AUTOCALL, KG_BLUETOOTH_MODE_MANUAL, KG_BLUETOOTH_MODE_VISIBLE,
KG_BLUETOOTH_MODE_MAX
}
List of possible values for blink mode.
Functions
void my_iwrap_callback_txcommand (uint16_t length, const uint8_t *data)
iWRAP TX command callback
void my_iwrap_callback_txdata (uint8_t channel, uint16_t length, const uint8_t *data)
iWRAP TX data callback
void my_iwrap_callback_rxoutput (uint16_t length, const uint8_t *data)
iWRAP RX output callback
void my_iwrap_callback_rxdata (uint8_t channel, uint16_t length, const uint8_t *data)
iWRAP RX data callback
void my_iwrap_rsp_call (uint8_t link_id)
iWRAP "CALL" response handler
void my_iwrap_rsp_inquiry_result (const iwrap_address_t *bd_addr, uint32_t class_of_device, int8_t rssi)
iWRAP "INQUIRY" result response handler
void my_iwrap_rsp_list_count (uint8_t num_of_connections)
iWRAP "LIST" count response handler
void my_iwrap_rsp_list_result (uint8_t link_id, const char *mode, uint16_t blocksize, uint32_t elapsed_time, uint16_t local_msc, uint16_t remote_msc, const iwrap_address_t *addr, uint16_t channel, uint8_t direction, uint8_t powermode, uint8_t role, uint8_t crypt, uint16_t buffer, uint8_t eretx)
iWRAP "LIST" result response handler
void my_iwrap_rsp_pair (const iwrap_address_t *address, uint8_t result)
iWRAP "PAIR" response handler
void my_iwrap_rsp_set (uint8_t category, const char *option, const char *value)
iWRAP "SET" response handler
void my_iwrap_evt_connect (uint8_t link_id, const char *type, uint16_t target, const iwrap_address_t *address)
iWRAP "CONNECT" event handler
void my_iwrap_evt_inquiry_extended (const iwrap_address_t *address, uint8_t length, const uint8_t *data)
iWRAP "INQUIRY_EXTENDED" event handler
void my_iwrap_evt_inquiry_partial (const iwrap_address_t *address, uint32_t class_of_device, const char *cached_name, int8_t rssi)
iWRAP "INQUIRY_PARTIAL" event handler
void my_iwrap_evt_name (const iwrap_address_t *address, const char *friendly_name)
iWRAP "NAME" event handler
void my_iwrap_evt_no_carrier (uint8_t link_id, uint16_t error_code, const char *message)
iWRAP "NO CARRIER" event handler
void my_iwrap_evt_pair (const iwrap_address_t *address, uint8_t key_type, const uint8_t *link_key)
iWRAP "PAIR" event handler
void my_iwrap_evt_ready ()
iWRAP "READY" event handler
void my_iwrap_evt_ring (uint8_t link_id, const iwrap_address_t *mac, uint16_t channel, const char *profile)
iWRAP "RING" event handler
uint8_t find_pairing_from_mac (const iwrap_address_t *mac)
Locate pairing index in connection map table from MAC address.
uint8_t find_pairing_from_link_id (uint8_t link_id)
Locate pairing index in connection map table from link ID.
void add_mapped_connection (uint8_t link_id, const iwrap_address_t *addr, const char *mode, uint16_t channel)
Add new connection to connection map table.
uint8_t remove_mapped_connection (uint8_t link_id)
Remove connection from connection map table.
int serial_out (const char *str)
iWRAP serial debug output function
int serial_out (const __FlashStringHelper *str)
iWRAP serial debug output function
int iwrap_out (int len, unsigned char *data)
iWRAP module output function
void setup_hostif_bt2 ()
Initialize Bluetooth v2 (iWRAP) subsystem.
uint8_t bluetooth_check_incoming_protocol_data ()
Check for new incoming data from iWRAP, called every iteration from check_incoming_protocol_data()
uint8_t bluetooth_send_keyglove_packet_buffer (uint8_t *buffer, uint8_t length, uint8_t specificInterface)
Send a KGAPI packet using the Bluetooth v2 (iWRAP) interface.
Variables
BTKeyboardWrapper BTKeyboard
Wrapper object for Teensy-like keyboard behavior and iWRAP raw HID report interface.
BTMouseWrapper BTMouse
Wrapper object for Teensy-like mouse behavior and iWRAP HID interface.
bool interfaceBT2Ready
General Bluetooth ready indicator.
bool interfaceBT2SerialReady
Bluetooth SPP connection active indicator.
uint8_t interfaceBT2SerialMode
Bluetooth SPP connection KGAPI mode.
bool interfaceBT2IAPReady
Bluetooth iAP connection active indicator.
uint8_t interfaceBT2IAPMode
Bluetooth IAP connection KGAPI mode.
bool interfaceBT2RawHIDReady
Bluetooth raw HID connection active indicator.
uint8_t interfaceBT2RawHIDMode
Bluetooth raw HID connection KGAPI mode.
bool interfaceBT2HIDReady
Bluetooth HID connection active indicator.
bool interfaceBT2HFPReady
Bluetooth HFP connection active indicator.
bool interfaceBT2AVRCPReady
Bluetooth AVRCP connection active indicator.
Detailed Description
Declarations for Bluetooth using Bluegiga's WT12 module and iWRAP.
Author
Jeff Rowberg
Date
2014-11-07
Definition in file support_bluetooth2_iwrap.h.
Enumeration Type Documentation
enum bluetooth_mode_t
List of possible values for blink mode.
Enumerator
KG_BLUETOOTH_MODE_DISABLED
Bluetooth is disabled, undiscoverable and unconnectable (radio off)
KG_BLUETOOTH_MODE_AUTOCALL
Bluetooth enabled and in autocall mode if any pairing entries exist.
KG_BLUETOOTH_MODE_MANUAL
Bluetooth enabled but will not autocall, and will be visible only if no pairings exist.
KG_BLUETOOTH_MODE_VISIBLE
Bluetooth enabled and will not autocall, but will be visible in inquiries at all times.
Definition at line 95 of file support_bluetooth2_iwrap.h.
Function Documentation
void add_mapped_connection (uint8_t link_id, const iwrap_address_t * mac, const char * mode, uint16_t channel)
Add new connection to connection map table.
Parameters
[in] link_id Link ID of connection
[in] mac MAC address of connected device
[in] mode Profile used for connection (e.g. "HID", "RFCOMM", etc.)
[in] channel RFCOMM or L2CAP channel of connection
Definition at line 1077 of file support_bluetooth2_iwrap.cpp.
Referenced by my_iwrap_evt_connect(), my_iwrap_evt_ring(), and my_iwrap_rsp_list_result().
uint8_t bluetooth_send_keyglove_packet_buffer (uint8_t * buffer, uint8_t length, uint8_t specificInterface)
Send a KGAPI packet using the Bluetooth v2 (iWRAP) interface.
Parameters
[in] buffer Outgoing packet buffer
[in] length Outgoing packet length
[in] specificInterface Which interface to use, or zero for all available
Returns
Result, zero for success or non-zero for error
Definition at line 455 of file support_bluetooth2_iwrap.cpp.
Referenced by send_keyglove_packet().
uint8_t find_pairing_from_link_id (uint8_t link_id)
Locate pairing index in connection map table from link ID.
Parameters
[in] link_id Link ID to use for reference
Returns
Index if found, -1 (0xFF) otherwise
Definition at line 1044 of file support_bluetooth2_iwrap.cpp.
uint8_t find_pairing_from_mac (const iwrap_address_t * mac)
Locate pairing index in connection map table from MAC address.
Parameters
[in] mac MAC address of device to find
Returns
Index if found, -1 (0xFF) otherwise
Definition at line 1022 of file support_bluetooth2_iwrap.cpp.
Referenced by add_mapped_connection(), my_iwrap_evt_inquiry_extended(), my_iwrap_evt_inquiry_partial(), my_iwrap_evt_name(), and my_iwrap_rsp_inquiry_result().
int iwrap_out (int len, unsigned char * data)
iWRAP module output function
Parameters
[in] len Length of data to send to module
[in] data Data to send to module
Returns
Result of output function call
Definition at line 1344 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_callback_rxdata (uint8_t channel, uint16_t length, const uint8_t * data)
iWRAP RX data callback
Parameters
[in] channel Which data channel the data came in up
[in] length Length of iWRAP data packet received
[in] data Buffer of iWRAP data packet bytes received
This function is called immediately after a line or frame of user data is received from an open iWRAP data channel. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 577 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_callback_rxoutput (uint16_t length, const uint8_t * data)
iWRAP RX output callback
Parameters
[in] length Length of iWRAP output received
[in] data Buffer of iWRAP output bytes received
This function is called immediately after a response/event line is fully received from the iWRAP command channel, before any relevant response or event handlers are called. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 540 of file support_bluetooth2_iwrap.cpp.
void my_iwrap_callback_txcommand (uint16_t length, const uint8_t * data)
iWRAP TX command callback
Parameters
[in] length Length of command sent
[in] data Buffer of command bytes sent
This function is called immediately before a command is sent out via the iWRAP UART interface. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 508 of file support_bluetooth2_iwrap.cpp.
void my_iwrap_callback_txdata (uint8_t channel, uint16_t length, const uint8_t * data)
iWRAP TX data callback
Parameters
[in] channel Which data channel the data came in up
[in] length Length of data sent
[in] data Buffer of data bytes sent
This function is called immediately before a data packet is sent out via the iWRAP UART interface. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 524 of file support_bluetooth2_iwrap.cpp.
void my_iwrap_evt_connect (uint8_t link_id, const char * type, uint16_t target, const iwrap_address_t * mac)
iWRAP "CONNECT" event handler
Parameters
[in] link_id Link ID assigned to this completed outgoing connection
[in] type Type of link opened (e.g. "HID", "HFP", etc.)
[in] target RFCOMM or L2CAP channel for this connection
[in] mac MAC address of remote device
Definition at line 845 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_inquiry_extended (const iwrap_address_t * mac, uint8_t length, const uint8_t * data)
iWRAP "INQUIRY_EXTENDED" event handler
Parameters
[in] mac MAC address of remote device
[in] length Length of raw extended inquiry data
[in] data Raw extended inquiry data
Definition at line 863 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_inquiry_partial (const iwrap_address_t * mac, uint32_t class_of_device, const char * cached_name, int8_t rssi)
iWRAP "INQUIRY_PARTIAL" event handler
Parameters
[in] mac MAC address of remote device
[in] class_of_device Bluetooth class of device
[in] cached_name Null-ternimated device name string
[in] rssi RSSI (signal strength) of remote device
Definition at line 893 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_name (const iwrap_address_t * mac, const char * friendly_name)
iWRAP "NAME" event handler
Parameters
[in] mac MAC address of remote device
[in] friendly_name Null-ternimated device name string
Definition at line 920 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_no_carrier (uint8_t link_id, uint16_t error_code, const char * message)
iWRAP "NO CARRIER" event handler
Parameters
[in] link_id Link ID of connection which just closed
[in] error_code Numeric error code
[in] message Description string for error
Definition at line 961 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_pair (const iwrap_address_t * mac, uint8_t key_type, const uint8_t * link_key)
iWRAP "PAIR" event handler
Parameters
[in] mac MAC address of remote device
[in] key_type Key type used during pairing
[in] link_key Encryption key generated during pairing
Definition at line 989 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_ring (uint8_t link_id, const iwrap_address_t * mac, uint16_t channel, const char * profile)
iWRAP "RING" event handler
Parameters
[in] link_id Link ID assigned to incoming connection
[in] mac MAC address of remote device
[in] channel RFCOMM or L2CAP channel for connection
[in] profile Profile used for connection (e.g. "HID", "AVRCP", etc.)
Definition at line 1007 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_call (uint8_t link_id)
iWRAP "CALL" response handler
Parameters
[in] link_id Link ID allocated to new pending outgoing call
Definition at line 592 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_inquiry_result (const iwrap_address_t * mac, uint32_t class_of_device, int8_t rssi)
iWRAP "INQUIRY" result response handler
Parameters
[in] mac MAC address of remote device
[in] class_of_device Bluetooth class of device
[in] rssi RSSI (signal strength) of device
Definition at line 635 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_list_count (uint8_t num_of_connections)
iWRAP "LIST" count response handler
Parameters
[in] num_of_connections Total number of active individual connections
Definition at line 661 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_list_result (uint8_t link_id, const char * mode, uint16_t blocksize, uint32_t elapsed_time, uint16_t local_msc, uint16_t remote_msc, const iwrap_address_t * mac, uint16_t channel, uint8_t direction, uint8_t powermode, uint8_t role, uint8_t crypt, uint16_t buffer, uint8_t eretx)
iWRAP "LIST" result response handler
Parameters
[in] link_id Link ID assigned to this connection
[in] mode Type of connection (profile used, e.g. "HID" or "HFP")
[in] blocksize MTU for this connection
[in] elapsed_time Number of seconds this connection has been active
[in] local_msc Local modem status control bits
[in] remote_msc Remote modem status control bits
[in] mac MAC address of remote device
[in] channel RFCOMM or L2CAP channel
[in] direction Outgoing (1) out incoming (2) connection
[in] powermode Active (1), hold (2), sniff (3), or park (4) mode
[in] role Master (1) or slave (2) role
[in] crypt Plaintext (1) or encrypted (2) connection
[in] buffer Number of bytes currently in iWRAP buffer for this link
[in] eretx Enhanced retransmission mode (0=disabled, 1=enabled)
Definition at line 682 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_pair (const iwrap_address_t * mac, uint8_t result)
iWRAP "PAIR" response handler
Parameters
[in] mac MAC address of remote device
[in] result Status of pairing attempt (0=success, 1=failure)
Definition at line 692 of file support_bluetooth2_iwrap.cpp.
Referenced by my_iwrap_evt_pair(), and setup_hostif_bt2().
void my_iwrap_rsp_set (uint8_t category, const char * option, const char * value)
iWRAP "SET" response handler
Parameters
[in] category Setting category (1=BT, 2=CONTROL, 3=PROFILE)
[in] option Option name (e.g. "BDADDR", "PAGEMODE", "MUX", "HID", etc.)
[in] value Option value (e.g. "00:07:80:AA:BB:CC", 4 2000 1", etc.)
Definition at line 781 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
uint8_t remove_mapped_connection (uint8_t link_id)
Remove connection from connection map table.
Parameters
[in] link_id Link ID of connection
Returns
Pairing index of device in table if found and removed, -1 (0xFF) otherwise
Definition at line 1179 of file support_bluetooth2_iwrap.cpp.
Referenced by my_iwrap_evt_no_carrier().
int serial_out (const char * str)
iWRAP serial debug output function
Parameters
[in] str Null-terminated string to send to host
Returns
Result of output function call
Definition at line 1323 of file support_bluetooth2_iwrap.cpp.
int serial_out (const __FlashStringHelper * str)
iWRAP serial debug output function
Parameters
[in] str Null-terminated flash-stored string to send to host
Returns
Result of output function call
Definition at line 1333 of file support_bluetooth2_iwrap.cpp.