Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_protocol.h File Reference
support_protocol.h File Reference
KGAPI protocol core declarations.
#include "support_protocol_system.h"
#include "support_protocol_touch.h"
#include "support_protocol_feedback.h"
#include "support_protocol_motion.h"
#include "support_protocol_flex.h"
#include "support_protocol_pressure.h"
#include "support_protocol_touchset.h"
#include "support_protocol_bluetooth.h"
#include "custom_protocol.h"
Macros
#define KG_PROTOCOL_RX_TIMEOUT 500
Number of milliseconds before KGAPI parser will timeout after an incomplete packet.
#define KG_PACKET_TYPE_EVENT 0x80
First byte in header of an event packet.
#define KG_PACKET_TYPE_COMMAND 0xC0
First byte in header of a command or response packet.
#define KG_PACKET_CLASS_PROTOCOL 0x00
#define KG_PACKET_CLASS_SYSTEM 0x01
#define KG_PACKET_CLASS_TOUCH 0x02
#define KG_PACKET_CLASS_FEEDBACK 0x03
#define KG_PACKET_CLASS_MOTION 0x04
#define KG_PACKET_CLASS_FLEX 0x05
#define KG_PACKET_CLASS_PRESSURE 0x06
#define KG_PACKET_CLASS_TOUCHSET 0x07
#define KG_PACKET_CLASS_BLUETOOTH 0x08
#define KG_LOG_LEVEL_PANIC 0
Log level for "What a Terrible Failure" problems that will lock the MCU.
#define KG_LOG_LEVEL_CRITICAL 1
Log level for critical issues that will break core functionality.
#define KG_LOG_LEVEL_WARNING 3
Log level for warnings that may impact certain subsystems.
#define KG_LOG_LEVEL_NORMAL 5
Log level for regular status updates.
#define KG_LOG_LEVEL_VERBOSE 9
Log level for extra detailed info.
#define KG_PACKET_ID_EVT_PROTOCOL_ERROR 0x01
#define KG_PROTOCOL_ERROR_INVALID_COMMAND 0x0001
#define KG_PROTOCOL_ERROR_PACKET_TIMEOUT 0x0002
#define KG_PROTOCOL_ERROR_BAD_LENGTH 0x0003
#define KG_PROTOCOL_ERROR_PARAMETER_LENGTH 0x0004
#define KG_PROTOCOL_ERROR_PARAMETER_RANGE 0x0005
#define KG_PROTOCOL_ERROR_NOT_IMPLEMENTED 0x0006
#define KG_PROTOCOL_ERROR_NULL_POINTER 0xADDE
Functions
uint8_t filter_incoming_keyglove_packet (uint8_t *rxPacket)
Custom filter for incoming command packets.
uint8_t filter_outgoing_keyglove_packet (uint8_t *packetType, uint8_t *payloadLength, uint8_t *packetClass, uint8_t *packetId, uint8_t *payload)
Custom filter for outgoing response/event packets.
uint8_t process_protocol_command_custom (uint8_t *rxPacket)
Custom command identification and execution.
uint8_t check_incoming_protocol_data ()
Check all relevant interfaces for any incoming protocol data.
uint8_t send_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t *payload)
Send an outgoing packet (response or event) immediately.
uint8_t queue_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t *payload)
Add an outgoing packet (response or event) to the queue to send later.
void setup_protocol ()
Initialize protocol buffers and BGAPI parser.
void protocol_parse (uint8_t inputByte)
Parse the next incoming KGAPI protocol byte.
uint16_t reset_keyglove_rx_packet ()
Set RX packet state back to "empty" state.
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const char *message)
Send a special log message (from RAM) out the main serial interface.
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const __FlashStringHelper *message)
Send a special log message (from flash) out the main serial interface.
uint16_t send_keyglove_queue ()
Check for and send next available queued packet (if any)
Variables
uint8_t(* kg_evt_protocol_error)(uint16_t code)
bool inBinPacket
Indicates whether we have started parsing a binary packet or not.
uint8_t binDataLength
Expected size of incoming binary data (should be rxPacketLength - 4)
uint8_t skipPacket
Global var to control whether event packet will be skipped due to custom handler.
uint8_t lastCommandInterfaceNum
Source interface number of last incoming command packet.
uint8_t systemResetFlags
Controls what to reset when we use "system_reset" API command.
Detailed Description
KGAPI protocol core declarations.
Author
Jeff Rowberg
Date
2014-11-07
Definition in file support_protocol.h.
Function Documentation
uint8_t check_incoming_protocol_data ()
Check all relevant interfaces for any incoming protocol data.
Returns
Result, zero for success or non-zero for error
Definition at line 216 of file support_protocol.cpp.
Referenced by loop().
uint8_t filter_incoming_keyglove_packet (uint8_t * rxPacket)
Custom filter for incoming command packets.
Parameters
[in,out] rxPacket Incoming packet byte array (guaranteed to be well-formed)
Returns
KGAPI command packet fallthrough, zero allows and non-zero prevents
This function should not be used to add support for new commands; it is only for filtering/modifying packets on-the-fly if desired. To add new commands, refer to the process_protocol_command_custom() function instead.
See also
protocol_parse()
process_protocol_command_custom()
Definition at line 55 of file custom_protocol.cpp.
Referenced by protocol_parse().
uint8_t filter_outgoing_keyglove_packet (uint8_t * packetType, uint8_t * payloadLength, uint8_t * packetClass, uint8_t * packetId, uint8_t * payload)
Custom filter for outgoing response/event packets.
Parameters
[in,out] packetType Packet type (0x80 = event, 0xC0 = response)
[in,out] payloadLength Length of packet payload data
[in,out] packetClass Packet class byte
[in,out] packetId Packet ID byte
[in,out] payload Packet payload data (may be 0 if payloadLength is 0)
Returns
KGAPI response/event packet fallthrough, zero allows and non-zero prevents
Definition at line 78 of file custom_protocol.cpp.
Referenced by send_keyglove_packet().
uint8_t process_protocol_command_custom (uint8_t * rxPacket)
Custom command identification and execution.
Parameters
[in] rxPacket Incoming command packet byte array (guaranteed to be well-formed)
Returns
KGAPI protocol error code after parsing/detecting command data
See also
protocol_parse()
Definition at line 98 of file custom_protocol.cpp.
Referenced by protocol_parse().
void protocol_parse (uint8_t inputByte)
Parse the next incoming KGAPI protocol byte.
Parameters
[in] inputByte Incoming byte to parse
Definition at line 97 of file support_protocol.cpp.
Referenced by check_incoming_protocol_data(), and my_iwrap_callback_rxdata().
uint8_t queue_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t * payload)
Add an outgoing packet (response or event) to the queue to send later.
Parameters
[in] packetType Type of packet to send
[in] payloadLength Number of bytes in data payload (0 or more)
[in] packetClass Packet class ID byte
[in] packetId Packet command ID byte
[in] payload Payload data byte array
Returns
Result, zero for success or non-zero for error
Definition at line 294 of file support_protocol.cpp.
Referenced by kg_cmd_bluetooth_get_connections(), and kg_cmd_bluetooth_get_pairings().
uint16_t reset_keyglove_rx_packet ()
Set RX packet state back to "empty" state.
Returns
Number of bytes in packet buffer at time of reset
Definition at line 86 of file support_protocol.cpp.
Referenced by kg_cmd_system_reset(), and protocol_parse().
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const char * message)
Send a special log message (from RAM) out the main serial interface.
Parameters
[in] level Log level
[in] length Number of bytes in message
[in] message Message to send (normal variable in RAM)
Returns
Result, zero for success or non-zero for error
Definition at line 264 of file support_protocol.cpp.
Referenced by bluetooth_check_incoming_protocol_data(), my_iwrap_callback_rxoutput(), my_iwrap_callback_txcommand(), my_iwrap_callback_txdata(), and update_motion_mpu6050_hand().
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const __FlashStringHelper * message)
Send a special log message (from flash) out the main serial interface.
Parameters
[in] level Log level
[in] length Number of bytes in message
[in] message Message to send (from flash)
Returns
Result, zero for success or non-zero for error
Definition at line 278 of file support_protocol.cpp.
uint8_t send_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t * payload)
Send an outgoing packet (response or event) immediately.
Parameters
[in] packetType Type of packet to send
[in] payloadLength Number of bytes in data payload (0 or more)
[in] packetClass Packet class ID byte
[in] packetId Packet command ID byte
[in] payload Payload data byte array
Returns
Result, zero for success or non-zero for error
Definition at line 327 of file support_protocol.cpp.
Referenced by add_mapped_connection(), bluetooth_check_incoming_protocol_data(), check_incoming_protocol_data(), find_pairing_from_link_id(), find_pairing_from_mac(), kg_cmd_bluetooth_set_mode(), kg_cmd_feedback_set_blink_mode(), kg_cmd_feedback_set_piezo_mode(), kg_cmd_feedback_set_rgb_mode(), kg_cmd_feedback_set_vibrate_mode(), kg_cmd_motion_set_mode(), kg_cmd_system_reset(), loop(), my_iwrap_evt_inquiry_extended(), my_iwrap_evt_inquiry_partial(), my_iwrap_evt_name(), my_iwrap_evt_no_carrier(), my_iwrap_rsp_call(), my_iwrap_rsp_inquiry_result(), my_iwrap_rsp_pair(), my_iwrap_rsp_set(), my_kg_evt_system_timer_tick(), process_protocol_command_bluetooth(), process_protocol_command_feedback(), process_protocol_command_motion(), process_protocol_command_system(), process_protocol_command_touch(), protocol_parse(), remove_mapped_connection(), send_keyglove_queue(), setup(), update_motion_mpu6050_hand(), and update_touch().
uint16_t send_keyglove_queue ()
Check for and send next available queued packet (if any)
Returns
Number of bytes still used in outgoing queue
See also
queue_keyglove_packet()
Definition at line 400 of file support_protocol.cpp.
Referenced by loop().