Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_feedback_vibrate.cpp File Reference
support_feedback_vibrate.cpp File Reference
Feedback implementations for vibration motor.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_feedback.h"
Functions
void feedback_set_vibrate_logic (uint8_t logic)
Sets vibration motor control pin logic state.
void feedback_set_vibrate_mode (feedback_vibrate_mode_t mode, uint8_t duration)
Sets the operational mode of the vibration motor.
void setup_feedback_vibrate ()
Initialize vibration feedback subsystem.
void update_feedback_vibrate ()
Update status of vibration feedback subystem, called at 100Hz from loop()
uint16_t kg_cmd_feedback_get_vibrate_mode (uint8_t index, uint8_t *mode, uint8_t *duration)
Get current feedback mode for a vibration motor.
uint16_t kg_cmd_feedback_set_vibrate_mode (uint8_t index, uint8_t mode, uint8_t duration)
Set a new vibration motor feedback mode.
Variables
feedback_vibrate_mode_t feedbackVibrateMode
Vibration mode.
uint16_t feedbackVibrateTick
Vibration tick reference.
uint16_t feedbackVibrateDuration
Vibration pattern duration.
Detailed Description
Feedback implementations for vibration motor.
Author
Jeff Rowberg
Date
2014-11-07
This file defines the feeback functionality for the vibration motor that may be included as an optional module in a Keyglove modular hardware design. This file is meant to contain only behavioral logic and abstracted functions that do not require specific pin knowledge of the selected MCU. Any pins used should be defined in the selected MCU board support file.
Normally it is not necessary to edit this file.
Definition in file support_feedback_vibrate.cpp.
Function Documentation
void feedback_set_vibrate_logic (uint8_t logic)
Sets vibration motor control pin logic state.
Parameters
[in] logic Zero for low (off), non-zero for high (on)
See also
KG_PIN_VIBRATE
Definition at line 58 of file support_feedback_vibrate.cpp.
Referenced by feedback_set_vibrate_mode(), and update_feedback_vibrate().
void feedback_set_vibrate_mode (feedback_vibrate_mode_t mode, uint8_t duration)
Sets the operational mode of the vibration motor.
Parameters
[in] mode Vibration mode to use
[in] duration Duration in 10ms units to run pattern before ending (0 to run forever)
Definition at line 67 of file support_feedback_vibrate.cpp.
Referenced by kg_cmd_feedback_set_vibrate_mode(), and update_feedback_vibrate().
uint16_t kg_cmd_feedback_get_vibrate_mode (uint8_t index, uint8_t * mode, uint8_t * duration)
Get current feedback mode for a vibration motor.
Parameters
[in] index Index of vibration device for which to get the current mode
[out] mode Current feedback mode for specified vibration device
[out] duration Duration to maintain vibration
Returns
Result code (0=success)
Definition at line 111 of file support_feedback_vibrate.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_vibrate_mode (uint8_t index, uint8_t mode, uint8_t duration)
Set a new vibration motor feedback mode.
Parameters
[in] index Index of vibration device for which to set a new mode
[in] mode New feedback mode to set for specified vibration device
[in] duration Duration to maintain vibration
Returns
Result code (0=success)
Definition at line 125 of file support_feedback_vibrate.cpp.
Referenced by process_protocol_command_feedback().