Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_bluetooth2_iwrap.cpp File Reference
support_bluetooth2_iwrap.cpp File Reference
Implementations for Bluetooth using Bluegiga's WT12 module and iWRAP.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_bluetooth2_iwrap.h"
Macros
#define BT2_RAWHID_RX_SIZE 16
Raw HID input payload size.
#define BT2_RAWHID_TX_SIZE 16
Raw HID output payload size.
Functions
void setup_hostif_bt2 ()
Initialize Bluetooth v2 (iWRAP) subsystem.
uint8_t bluetooth_check_incoming_protocol_data ()
Check for new incoming data from iWRAP, called every iteration from check_incoming_protocol_data()
uint8_t bluetooth_send_keyglove_packet_buffer (uint8_t *buffer, uint8_t length, uint8_t specificInterface)
Send a KGAPI packet using the Bluetooth v2 (iWRAP) interface.
void my_iwrap_callback_txcommand (uint16_t length, const uint8_t *data)
iWRAP TX command callback
void my_iwrap_callback_txdata (uint8_t channel, uint16_t length, const uint8_t *data)
iWRAP TX data callback
void my_iwrap_callback_rxoutput (uint16_t length, const uint8_t *data)
iWRAP RX output callback
void my_iwrap_callback_rxdata (uint8_t channel, uint16_t length, const uint8_t *data)
iWRAP RX data callback
void my_iwrap_rsp_call (uint8_t link_id)
iWRAP "CALL" response handler
void my_iwrap_rsp_inquiry_result (const iwrap_address_t *mac, uint32_t class_of_device, int8_t rssi)
iWRAP "INQUIRY" result response handler
void my_iwrap_rsp_list_count (uint8_t num_of_connections)
iWRAP "LIST" count response handler
void my_iwrap_rsp_list_result (uint8_t link_id, const char *mode, uint16_t blocksize, uint32_t elapsed_time, uint16_t local_msc, uint16_t remote_msc, const iwrap_address_t *mac, uint16_t channel, uint8_t direction, uint8_t powermode, uint8_t role, uint8_t crypt, uint16_t buffer, uint8_t eretx)
iWRAP "LIST" result response handler
void my_iwrap_rsp_pair (const iwrap_address_t *mac, uint8_t result)
iWRAP "PAIR" response handler
void my_iwrap_rsp_set (uint8_t category, const char *option, const char *value)
iWRAP "SET" response handler
void my_iwrap_evt_connect (uint8_t link_id, const char *type, uint16_t target, const iwrap_address_t *mac)
iWRAP "CONNECT" event handler
void my_iwrap_evt_inquiry_extended (const iwrap_address_t *mac, uint8_t length, const uint8_t *data)
iWRAP "INQUIRY_EXTENDED" event handler
void my_iwrap_evt_inquiry_partial (const iwrap_address_t *mac, uint32_t class_of_device, const char *cached_name, int8_t rssi)
iWRAP "INQUIRY_PARTIAL" event handler
void my_iwrap_evt_name (const iwrap_address_t *mac, const char *friendly_name)
iWRAP "NAME" event handler
void my_iwrap_evt_no_carrier (uint8_t link_id, uint16_t error_code, const char *message)
iWRAP "NO CARRIER" event handler
void my_iwrap_evt_pair (const iwrap_address_t *mac, uint8_t key_type, const uint8_t *link_key)
iWRAP "PAIR" event handler
void my_iwrap_evt_ready ()
iWRAP "READY" event handler
void my_iwrap_evt_ring (uint8_t link_id, const iwrap_address_t *mac, uint16_t channel, const char *profile)
iWRAP "RING" event handler
uint8_t find_pairing_from_mac (const iwrap_address_t *mac)
Locate pairing index in connection map table from MAC address.
uint8_t find_pairing_from_link_id (uint8_t link_id)
Locate pairing index in connection map table from link ID.
void add_mapped_connection (uint8_t link_id, const iwrap_address_t *mac, const char *mode, uint16_t channel)
Add new connection to connection map table.
uint8_t remove_mapped_connection (uint8_t link_id)
Remove connection from connection map table.
int serial_out (const char *str)
iWRAP serial debug output function
int serial_out (const __FlashStringHelper *str)
iWRAP serial debug output function
int iwrap_out (int len, unsigned char *data)
iWRAP module output function
uint16_t kg_cmd_bluetooth_get_mode (uint8_t *mode)
Get current mode for Bluetooth subsystem.
uint16_t kg_cmd_bluetooth_set_mode (uint8_t mode)
Set new mode for Bluetooth subsystem.
uint16_t kg_cmd_bluetooth_reset ()
Reset Bluetooth subsystem.
uint16_t kg_cmd_bluetooth_get_mac (uint8_t *address)
Get local Bluetooth MAC address.
uint16_t kg_cmd_bluetooth_get_pairings (uint8_t *count)
Get a list of all paired devices.
uint16_t kg_cmd_bluetooth_discover (uint8_t duration)
Perform Bluetooth inquiry to locate nearby devices.
uint16_t kg_cmd_bluetooth_pair (uint8_t *address)
Initiate pairing request to remote device.
uint16_t kg_cmd_bluetooth_delete_pairing (uint8_t index)
Remove a specific pairing entry.
uint16_t kg_cmd_bluetooth_clear_pairings ()
Remove all pairing entries.
uint16_t kg_cmd_bluetooth_get_connections (uint8_t *count)
Get a list of all open or pending connections.
uint16_t kg_cmd_bluetooth_connect (uint8_t index, uint8_t profile)
Attempt to open a connection to a specific paired device using a specific profile.
uint16_t kg_cmd_bluetooth_disconnect (uint8_t handle)
Close a specific Bluetooth connection.
Variables
uint8_t bluetoothTXHIDKBPacket [12]
Buffer for outgoing HID keyboard report payload.
uint8_t bluetoothTXHIDCPPacket [7]
Buffer for outgoing HID consumer page report payload.
uint8_t bluetoothTXHIDMousePacket [9]
Buffer for outgoing HID mouse report payload.
uint8_t bluetoothRXRawHIDPacket [16+4]
Buffer for incoming raw HID report.
uint8_t bluetoothTXRawHIDPacket [16+4]
Buffer for outgoing raw HID report.
bool interfaceBT2Ready = false
General Bluetooth ready indicator.
bool interfaceBT2SerialReady = false
Bluetooth SPP connection active indicator.
uint8_t interfaceBT2SerialMode = 0x01 | 0x02
Bluetooth SPP connection KGAPI mode.
bool interfaceBT2IAPReady = false
Bluetooth iAP connection active indicator.
uint8_t interfaceBT2IAPMode = 0x01 | 0x02
Bluetooth IAP connection KGAPI mode.
bool interfaceBT2RawHIDReady = false
Bluetooth raw HID connection active indicator.
uint8_t interfaceBT2RawHIDMode = 0x02
Bluetooth raw HID connection KGAPI mode.
bool interfaceBT2HIDReady = false
Bluetooth HID connection active indicator.
bool interfaceBT2HFPReady = false
Bluetooth HFP connection active indicator.
bool interfaceBT2AVRCPReady = false
Bluetooth AVRCP connection active indicator.
iwrap_pairing_t * iwrap_connection_map [16]
Array of paired devices for connection mapping.
uint8_t iwrap_mode = IWRAP_MODE_MUX
iWRAP UART interface mode
uint8_t iwrap_state = 1
Current iWRAP state.
uint8_t iwrap_initialized = 0
Flag indicating iWRAP initialization status.
uint8_t iwrap_page_mode = 0
Current Bluetooth page mode (visible/connectable)
uint8_t iwrap_pairings = 0
Number of paired devices known.
uint8_t iwrap_pending_calls = 0
Number of pending outgoing calls (should always be 0 or 1)
uint8_t iwrap_pending_call_link_id = 0xFF
Link ID assigned to pending call, if any.
uint8_t iwrap_connected_devices = 0
Number of unique connected devices.
uint8_t iwrap_active_connections = 0
Total number of active links.
uint8_t iwrap_autocall_target = 0
How many unique devices should autocall attempt to connect to.
uint8_t iwrap_autocall_index = 0
Current pairing entry index for next autocall attempt.
iwrap_address_t iwrap_module_mac
Local Bluetooth module's MAC address.
uint8_t bluetoothSPPDeviceIndex = 0
Pairing index for device with active/selected SPP connection.
uint8_t bluetoothIAPDeviceIndex = 0
Pairing index for device with active/selected iAP connection.
uint8_t bluetoothHIDDeviceIndex = 0
Pairing index for device with active/selected HID connection.
uint8_t bluetoothRawHIDDeviceIndex = 0
Pairing index for device with active/selected raw HID connection.
uint8_t bluetoothHFPDeviceIndex = 0
Pairing index for device with active/selected HFP connection.
uint8_t bluetoothAVRCPDeviceIndex = 0
Pairing index for device with active/selected AVRCP connection.
bluetooth_mode_t bluetoothMode = KG_BLUETOOTH_MODE_DISABLED
Current Bluetooth subsystem mode.
uint32_t bluetoothTock = 0
1 Hz counter for tracking certain Bluetooth activities
uint16_t bluetoothPendingConnectionStatus = 0xFFFF
Bitmask for which connections should have status update events triggered (0-15)
uint8_t bluetoothPendingCallPairIndex = 0
Pairing index for device with pending call active.
uint8_t bluetoothPendingCallProfile = 0
Bitmask for which profile was used for pending call.
uint16_t bluetoothActiveLinkMask = 0x0000
Bitmask for which link IDs are currently allocated to active links (0-15)
BTKeyboardWrapper BTKeyboard
Wrapper object for Teensy-like keyboard behavior and iWRAP raw HID report interface.
BTMouseWrapper BTMouse
Wrapper object for Teensy-like mouse behavior and iWRAP HID interface.
Detailed Description
Implementations for Bluetooth using Bluegiga's WT12 module and iWRAP.
Author
Jeff Rowberg
Date
2014-11-07
This file provides an interface between KGAPI and the full-featured iWRAP firmware that runs on Bluegiga's WT12 class 2 Bluetooth module. This code relies on a separate iWRAP parser library for the Arduino platform, and correlates various iWRAP commands and events into API methods which are more specifically useful in the Keyglove environment.
Normally it is not necessary to edit this file.
Manual instructions for WT12 setup:
Update WT12 firmware to iWRAP5 build 800 or later
Reset to default settings ("SET RESET")
Clear existing pairings ("SET BT PAIR *")
Apply the following settings
 SET BT NAME Keyglove
 SET BT CLASS 00540
 SET BT IDENT USB:1d50 6025 1.0.0 Keyglove Input Device
 SET BT SSP 3 0
 SET BT SNIFF 20 10 2 8 10
 SET CONTROL CD 80 2 20
 SET CONTROL ESCAPE - 40 1
 SET PROFILE HID 1f 40 100 0 en 0409 Keyglove Input Device
 HID SET F2 05010906A1010507850119E029E715002501750195088102950175088101950575010508850119012905910295017503910395067508150025650507190029658100C0050C0901A1018502050C1500250109E909EA09E209CD19B529B87501950881020A8A010A21020A2A021A23022A27027501950881020A83010A96010A92010A9E010A94010A060209B209B4750195088102C005010902A1010901A10085030509190129031500250195037501810295017505810305010930093109381581257F750895038106050C0A380295018106C0C006ABFF0A0002A10185047508150026FF00951009018102951009029102C0
 SET CONTROL CONFIG 3400 0048 50A1
 SET CONTROL ECHO 5
 SET CONTROL BAUD 125000,8n1
Change to 125000 baud and apply this setting:
 SET CONTROL MUX 1
Make SURE you power-cycle or reset the module after this point so that all settings take effect.
Basic Bluetooth Functionality:
Defaults to discoverable/connectable if no pairings
Defaults to undiscoverable/connectable if 1+ pairings
Automatically connect to first paired device on startup
Definition in file support_bluetooth2_iwrap.cpp.
Function Documentation
void add_mapped_connection (uint8_t link_id, const iwrap_address_t * mac, const char * mode, uint16_t channel)
Add new connection to connection map table.
Parameters
[in] link_id Link ID of connection
[in] mac MAC address of connected device
[in] mode Profile used for connection (e.g. "HID", "RFCOMM", etc.)
[in] channel RFCOMM or L2CAP channel of connection
Definition at line 1077 of file support_bluetooth2_iwrap.cpp.
Referenced by my_iwrap_evt_connect(), my_iwrap_evt_ring(), and my_iwrap_rsp_list_result().
uint8_t bluetooth_send_keyglove_packet_buffer (uint8_t * buffer, uint8_t length, uint8_t specificInterface)
Send a KGAPI packet using the Bluetooth v2 (iWRAP) interface.
Parameters
[in] buffer Outgoing packet buffer
[in] length Outgoing packet length
[in] specificInterface Which interface to use, or zero for all available
Returns
Result, zero for success or non-zero for error
Definition at line 455 of file support_bluetooth2_iwrap.cpp.
Referenced by send_keyglove_packet().
uint8_t find_pairing_from_link_id (uint8_t link_id)
Locate pairing index in connection map table from link ID.
Parameters
[in] link_id Link ID to use for reference
Returns
Index if found, -1 (0xFF) otherwise
Definition at line 1044 of file support_bluetooth2_iwrap.cpp.
uint8_t find_pairing_from_mac (const iwrap_address_t * mac)
Locate pairing index in connection map table from MAC address.
Parameters
[in] mac MAC address of device to find
Returns
Index if found, -1 (0xFF) otherwise
Definition at line 1022 of file support_bluetooth2_iwrap.cpp.
Referenced by add_mapped_connection(), my_iwrap_evt_inquiry_extended(), my_iwrap_evt_inquiry_partial(), my_iwrap_evt_name(), and my_iwrap_rsp_inquiry_result().
int iwrap_out (int len, unsigned char * data)
iWRAP module output function
Parameters
[in] len Length of data to send to module
[in] data Data to send to module
Returns
Result of output function call
Definition at line 1344 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
uint16_t kg_cmd_bluetooth_clear_pairings ()
Remove all pairing entries.
Returns
Result code (0=success)
Definition at line 1649 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_connect (uint8_t index, uint8_t profile)
Attempt to open a connection to a specific paired device using a specific profile.
Parameters
[in] index Index of pairing to use
[in] profile Profile to use for connection
Returns
Result code (0=success)
Definition at line 1737 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_delete_pairing (uint8_t index)
Remove a specific pairing entry.
Parameters
[in] index Index of pairing to delete
Returns
Result code (0=success)
Definition at line 1610 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_disconnect (uint8_t handle)
Close a specific Bluetooth connection.
Parameters
[in] handle Link ID of connection to close
Returns
Result code (0=success)
Definition at line 1806 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_discover (uint8_t duration)
Perform Bluetooth inquiry to locate nearby devices.
Parameters
[in] duration Number of seconds to run discovery process
Returns
Result code (0=success)
Definition at line 1554 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_connections (uint8_t * count)
Get a list of all open or pending connections.
Parameters
[out] count Number of open or pending connections
Returns
Result code (0=success)
Definition at line 1664 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_mac (uint8_t * address)
Get local Bluetooth MAC address.
Parameters
[out] address Local six-byte Bluetooth MAC address
Returns
Result code (0=success)
Definition at line 1481 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_mode (uint8_t * mode)
Get current mode for Bluetooth subsystem.
Parameters
[out] mode Current Bluetooth mode
Returns
Result code (0=success)
Definition at line 1358 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_get_pairings (uint8_t * count)
Get a list of all paired devices.
Parameters
[out] count Number of paired devices
Returns
Result code (0=success)
Definition at line 1500 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_pair (uint8_t * address)
Initiate pairing request to remote device.
Parameters
[in] address Six-byte Bluetooth MAC address of remote device to pair with
Returns
Result code (0=success)
Definition at line 1586 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth().
uint16_t kg_cmd_bluetooth_reset ()
Reset Bluetooth subsystem.
Returns
Result code (0=success)
Definition at line 1463 of file support_bluetooth2_iwrap.cpp.
Referenced by process_protocol_command_bluetooth(), and setup().
uint16_t kg_cmd_bluetooth_set_mode (uint8_t mode)
Set new mode for Bluetooth subsystem.
Parameters
[in] mode New Bluetooth mode to set
Returns
Result code (0=success)
Definition at line 1373 of file support_bluetooth2_iwrap.cpp.
Referenced by my_kg_evt_bluetooth_ready(), and process_protocol_command_bluetooth().
void my_iwrap_callback_rxdata (uint8_t channel, uint16_t length, const uint8_t * data)
iWRAP RX data callback
Parameters
[in] channel Which data channel the data came in up
[in] length Length of iWRAP data packet received
[in] data Buffer of iWRAP data packet bytes received
This function is called immediately after a line or frame of user data is received from an open iWRAP data channel. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 577 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_callback_rxoutput (uint16_t length, const uint8_t * data)
iWRAP RX output callback
Parameters
[in] length Length of iWRAP output received
[in] data Buffer of iWRAP output bytes received
This function is called immediately after a response/event line is fully received from the iWRAP command channel, before any relevant response or event handlers are called. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 540 of file support_bluetooth2_iwrap.cpp.
void my_iwrap_callback_txcommand (uint16_t length, const uint8_t * data)
iWRAP TX command callback
Parameters
[in] length Length of command sent
[in] data Buffer of command bytes sent
This function is called immediately before a command is sent out via the iWRAP UART interface. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 508 of file support_bluetooth2_iwrap.cpp.
void my_iwrap_callback_txdata (uint8_t channel, uint16_t length, const uint8_t * data)
iWRAP TX data callback
Parameters
[in] channel Which data channel the data came in up
[in] length Length of data sent
[in] data Buffer of data bytes sent
This function is called immediately before a data packet is sent out via the iWRAP UART interface. No MUX encapsulation is shown even if MUX mode is enabled.
Definition at line 524 of file support_bluetooth2_iwrap.cpp.
void my_iwrap_evt_connect (uint8_t link_id, const char * type, uint16_t target, const iwrap_address_t * mac)
iWRAP "CONNECT" event handler
Parameters
[in] link_id Link ID assigned to this completed outgoing connection
[in] type Type of link opened (e.g. "HID", "HFP", etc.)
[in] target RFCOMM or L2CAP channel for this connection
[in] mac MAC address of remote device
Definition at line 845 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_inquiry_extended (const iwrap_address_t * mac, uint8_t length, const uint8_t * data)
iWRAP "INQUIRY_EXTENDED" event handler
Parameters
[in] mac MAC address of remote device
[in] length Length of raw extended inquiry data
[in] data Raw extended inquiry data
Definition at line 863 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_inquiry_partial (const iwrap_address_t * mac, uint32_t class_of_device, const char * cached_name, int8_t rssi)
iWRAP "INQUIRY_PARTIAL" event handler
Parameters
[in] mac MAC address of remote device
[in] class_of_device Bluetooth class of device
[in] cached_name Null-ternimated device name string
[in] rssi RSSI (signal strength) of remote device
Definition at line 893 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_name (const iwrap_address_t * mac, const char * friendly_name)
iWRAP "NAME" event handler
Parameters
[in] mac MAC address of remote device
[in] friendly_name Null-ternimated device name string
Definition at line 920 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_no_carrier (uint8_t link_id, uint16_t error_code, const char * message)
iWRAP "NO CARRIER" event handler
Parameters
[in] link_id Link ID of connection which just closed
[in] error_code Numeric error code
[in] message Description string for error
Definition at line 961 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_pair (const iwrap_address_t * mac, uint8_t key_type, const uint8_t * link_key)
iWRAP "PAIR" event handler
Parameters
[in] mac MAC address of remote device
[in] key_type Key type used during pairing
[in] link_key Encryption key generated during pairing
Definition at line 989 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_evt_ring (uint8_t link_id, const iwrap_address_t * mac, uint16_t channel, const char * profile)
iWRAP "RING" event handler
Parameters
[in] link_id Link ID assigned to incoming connection
[in] mac MAC address of remote device
[in] channel RFCOMM or L2CAP channel for connection
[in] profile Profile used for connection (e.g. "HID", "AVRCP", etc.)
Definition at line 1007 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_call (uint8_t link_id)
iWRAP "CALL" response handler
Parameters
[in] link_id Link ID allocated to new pending outgoing call
Definition at line 592 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_inquiry_result (const iwrap_address_t * mac, uint32_t class_of_device, int8_t rssi)
iWRAP "INQUIRY" result response handler
Parameters
[in] mac MAC address of remote device
[in] class_of_device Bluetooth class of device
[in] rssi RSSI (signal strength) of device
Definition at line 635 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_list_count (uint8_t num_of_connections)
iWRAP "LIST" count response handler
Parameters
[in] num_of_connections Total number of active individual connections
Definition at line 661 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_list_result (uint8_t link_id, const char * mode, uint16_t blocksize, uint32_t elapsed_time, uint16_t local_msc, uint16_t remote_msc, const iwrap_address_t * mac, uint16_t channel, uint8_t direction, uint8_t powermode, uint8_t role, uint8_t crypt, uint16_t buffer, uint8_t eretx)
iWRAP "LIST" result response handler
Parameters
[in] link_id Link ID assigned to this connection
[in] mode Type of connection (profile used, e.g. "HID" or "HFP")
[in] blocksize MTU for this connection
[in] elapsed_time Number of seconds this connection has been active
[in] local_msc Local modem status control bits
[in] remote_msc Remote modem status control bits
[in] mac MAC address of remote device
[in] channel RFCOMM or L2CAP channel
[in] direction Outgoing (1) out incoming (2) connection
[in] powermode Active (1), hold (2), sniff (3), or park (4) mode
[in] role Master (1) or slave (2) role
[in] crypt Plaintext (1) or encrypted (2) connection
[in] buffer Number of bytes currently in iWRAP buffer for this link
[in] eretx Enhanced retransmission mode (0=disabled, 1=enabled)
Definition at line 682 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
void my_iwrap_rsp_pair (const iwrap_address_t * mac, uint8_t result)
iWRAP "PAIR" response handler
Parameters
[in] mac MAC address of remote device
[in] result Status of pairing attempt (0=success, 1=failure)
Definition at line 692 of file support_bluetooth2_iwrap.cpp.
Referenced by my_iwrap_evt_pair(), and setup_hostif_bt2().
void my_iwrap_rsp_set (uint8_t category, const char * option, const char * value)
iWRAP "SET" response handler
Parameters
[in] category Setting category (1=BT, 2=CONTROL, 3=PROFILE)
[in] option Option name (e.g. "BDADDR", "PAGEMODE", "MUX", "HID", etc.)
[in] value Option value (e.g. "00:07:80:AA:BB:CC", 4 2000 1", etc.)
Definition at line 781 of file support_bluetooth2_iwrap.cpp.
Referenced by setup_hostif_bt2().
uint8_t remove_mapped_connection (uint8_t link_id)
Remove connection from connection map table.
Parameters
[in] link_id Link ID of connection
Returns
Pairing index of device in table if found and removed, -1 (0xFF) otherwise
Definition at line 1179 of file support_bluetooth2_iwrap.cpp.
Referenced by my_iwrap_evt_no_carrier().
int serial_out (const char * str)
iWRAP serial debug output function
Parameters
[in] str Null-terminated string to send to host
Returns
Result of output function call
Definition at line 1323 of file support_bluetooth2_iwrap.cpp.
int serial_out (const __FlashStringHelper * str)
iWRAP serial debug output function
Parameters
[in] str Null-terminated flash-stored string to send to host
Returns
Result of output function call
Definition at line 1333 of file support_bluetooth2_iwrap.cpp.