Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_protocol.cpp File Reference
support_protocol.cpp File Reference
KGAPI protocol core implementations.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
Functions
void setup_protocol ()
Initialize protocol buffers and BGAPI parser.
uint16_t reset_keyglove_rx_packet ()
Set RX packet state back to "empty" state.
void protocol_parse (uint8_t inputByte)
Parse the next incoming KGAPI protocol byte.
uint8_t check_incoming_protocol_data ()
Check all relevant interfaces for any incoming protocol data.
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const char *message)
Send a special log message (from RAM) out the main serial interface.
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const __FlashStringHelper *message)
Send a special log message (from flash) out the main serial interface.
uint8_t queue_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t *payload)
Add an outgoing packet (response or event) to the queue to send later.
uint8_t send_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t *payload)
Send an outgoing packet (response or event) immediately.
uint16_t send_keyglove_queue ()
Check for and send next available queued packet (if any)
Variables
uint16_t rxByte
Container for incoming byte (actually WORD but the high byte is for .read() error checking)
uint8_t * rxPacket
Dynamic buffer for incoming KGAPI data.
uint16_t rxPacketSize
Current size of container for received packet buffer.
uint16_t rxPacketLength
Full length in bytes of received packet (may be less than rxPacketSize)
uint32_t packetStartTime
Incoming command packet timeout detection reference.
uint8_t * txQueue
Dynamic buffer for TX packet queue.
uint16_t txQueueSize
Allocated memory for the TX queue.
uint16_t txQueueLength
Number of bytes used in the TX queue.
bool inBinPacket = false
Indicates whether we have started parsing a binary packet or not.
uint8_t binDataLength
Expected size of incoming binary data (should be rxPacketLength - 4)
uint8_t skipPacket = 0
Global var to control whether event packet will be skipped due to custom handler.
uint8_t lastCommandInterfaceNum
Source interface number of last incoming command packet.
uint8_t systemResetFlags = 0
Controls what to reset when we use "system_reset" API command.
uint8_t(* kg_evt_protocol_error)(uint16_t code)=0
Detailed Description
KGAPI protocol core implementations.
Author
Jeff Rowberg
Date
2014-11-07
This file implements the structure behind the Keyglove binary API protocol. The incoming data stream parsing routines, error detection, timeout handling, packet queuing, and packet sending functionality is all here. A few core API commands and events are also implemented here. Subsystem-specific API packets are defined and implemented elsewhere.
Normally it is not necessary to edit this file.
Definition in file support_protocol.cpp.
Function Documentation
uint8_t check_incoming_protocol_data ()
Check all relevant interfaces for any incoming protocol data.
Returns
Result, zero for success or non-zero for error
Definition at line 216 of file support_protocol.cpp.
Referenced by loop().
void protocol_parse (uint8_t inputByte)
Parse the next incoming KGAPI protocol byte.
Parameters
[in] inputByte Incoming byte to parse
Definition at line 97 of file support_protocol.cpp.
Referenced by check_incoming_protocol_data(), and my_iwrap_callback_rxdata().
uint8_t queue_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t * payload)
Add an outgoing packet (response or event) to the queue to send later.
Parameters
[in] packetType Type of packet to send
[in] payloadLength Number of bytes in data payload (0 or more)
[in] packetClass Packet class ID byte
[in] packetId Packet command ID byte
[in] payload Payload data byte array
Returns
Result, zero for success or non-zero for error
Definition at line 294 of file support_protocol.cpp.
Referenced by kg_cmd_bluetooth_get_connections(), and kg_cmd_bluetooth_get_pairings().
uint16_t reset_keyglove_rx_packet ()
Set RX packet state back to "empty" state.
Returns
Number of bytes in packet buffer at time of reset
Definition at line 86 of file support_protocol.cpp.
Referenced by kg_cmd_system_reset(), and protocol_parse().
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const char * message)
Send a special log message (from RAM) out the main serial interface.
Parameters
[in] level Log level
[in] length Number of bytes in message
[in] message Message to send (normal variable in RAM)
Returns
Result, zero for success or non-zero for error
Definition at line 264 of file support_protocol.cpp.
Referenced by bluetooth_check_incoming_protocol_data(), my_iwrap_callback_rxoutput(), my_iwrap_callback_txcommand(), my_iwrap_callback_txdata(), and update_motion_mpu6050_hand().
uint8_t send_keyglove_log (uint8_t level, uint8_t length, const __FlashStringHelper * message)
Send a special log message (from flash) out the main serial interface.
Parameters
[in] level Log level
[in] length Number of bytes in message
[in] message Message to send (from flash)
Returns
Result, zero for success or non-zero for error
Definition at line 278 of file support_protocol.cpp.
uint8_t send_keyglove_packet (uint8_t packetType, uint8_t payloadLength, uint8_t packetClass, uint8_t packetId, uint8_t * payload)
Send an outgoing packet (response or event) immediately.
Parameters
[in] packetType Type of packet to send
[in] payloadLength Number of bytes in data payload (0 or more)
[in] packetClass Packet class ID byte
[in] packetId Packet command ID byte
[in] payload Payload data byte array
Returns
Result, zero for success or non-zero for error
Definition at line 327 of file support_protocol.cpp.
Referenced by add_mapped_connection(), bluetooth_check_incoming_protocol_data(), check_incoming_protocol_data(), find_pairing_from_link_id(), find_pairing_from_mac(), kg_cmd_bluetooth_set_mode(), kg_cmd_feedback_set_blink_mode(), kg_cmd_feedback_set_piezo_mode(), kg_cmd_feedback_set_rgb_mode(), kg_cmd_feedback_set_vibrate_mode(), kg_cmd_motion_set_mode(), kg_cmd_system_reset(), loop(), my_iwrap_evt_inquiry_extended(), my_iwrap_evt_inquiry_partial(), my_iwrap_evt_name(), my_iwrap_evt_no_carrier(), my_iwrap_rsp_call(), my_iwrap_rsp_inquiry_result(), my_iwrap_rsp_pair(), my_iwrap_rsp_set(), my_kg_evt_system_timer_tick(), process_protocol_command_bluetooth(), process_protocol_command_feedback(), process_protocol_command_motion(), process_protocol_command_system(), process_protocol_command_touch(), protocol_parse(), remove_mapped_connection(), send_keyglove_queue(), setup(), update_motion_mpu6050_hand(), and update_touch().
uint16_t send_keyglove_queue ()
Check for and send next available queued packet (if any)
Returns
Number of bytes still used in outgoing queue
See also
queue_keyglove_packet()
Definition at line 400 of file support_protocol.cpp.
Referenced by loop().