Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_feedback_piezo.h File Reference
support_feedback_piezo.h File Reference
Feedback declarations for piezo buzzer.
Macros
#define KG_PIEZO_DEFAULT_FREQ 1760
Default frequency (high A, 440Hz * 4)
Enumerations
enum feedback_piezo_mode_t {
KG_PIEZO_MODE_OFF = 0, KG_PIEZO_MODE_SOLID, KG_PIEZO_MODE_LONGBEEP, KG_PIEZO_MODE_LONGPULSE,
KG_PIEZO_MODE_SHORTBEEP, KG_PIEZO_MODE_SHORTPULSE, KG_PIEZO_MODE_TINYBEEP, KG_PIEZO_MODE_TINYPULSE,
KG_PIEZO_MODE_MAX
}
List of possible values for piezo mode.
Functions
void feedback_set_piezo_tone (uint16_t frequency)
Enables or disables the piezo buzzer using a certain frequency.
void feedback_set_piezo_mode (feedback_piezo_mode_t mode, uint8_t duration, uint16_t frequency)
Sets the operational mode of the piezo buzzer.
void setup_feedback_piezo ()
Initialize piezo feedback subsystem.
void update_feedback_piezo ()
Update status of piezo feedback subystem, called at 100Hz from loop()
Detailed Description
Feedback declarations for piezo buzzer.
Author
Jeff Rowberg
Date
2014-11-07
Definition in file support_feedback_piezo.h.
Enumeration Type Documentation
enum feedback_piezo_mode_t
List of possible values for piezo mode.
Enumerator
KG_PIEZO_MODE_OFF
(0) Buzzer solid off
KG_PIEZO_MODE_SOLID
(1) Buzzer solid on
KG_PIEZO_MODE_LONGBEEP
(2) Buzzer alternating at 1sec period, 500ms pulse
KG_PIEZO_MODE_LONGPULSE
(3) Buzzer alternating at 1sec period, 250ms pulse
KG_PIEZO_MODE_SHORTBEEP
(4) Buzzer alternating at 200ms period, 100ms pulse
KG_PIEZO_MODE_SHORTPULSE
(5) Buzzer alternating at 200ms period, 50ms pulse
KG_PIEZO_MODE_TINYBEEP
(6) Buzzer alternating at 100ms period, 50ms pulse
KG_PIEZO_MODE_TINYPULSE
(7) Buzzer alternating at 100ms period, 20ms pulse
Definition at line 43 of file support_feedback_piezo.h.
Function Documentation
void feedback_set_piezo_mode (feedback_piezo_mode_t mode, uint8_t duration, uint16_t frequency)
Sets the operational mode of the piezo buzzer.
Parameters
[in] mode Piezo mode to use
[in] duration Duration in 10ms units to run pattern before ending (0 to run forever)
[in] frequency Frequency (Hz) of tone to generate
Definition at line 73 of file support_feedback_piezo.cpp.
Referenced by kg_cmd_feedback_set_piezo_mode(), and update_feedback_piezo().
void feedback_set_piezo_tone (uint16_t frequency)
Enables or disables the piezo buzzer using a certain frequency.
Parameters
[in] frequency Frequency (Hz) of tone to generate, or zero to disable
See also
KG_PIN_PIEZO
Definition at line 59 of file support_feedback_piezo.cpp.
Referenced by feedback_set_piezo_mode(), and update_feedback_piezo().