Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_protocol_touch.h File Reference
support_protocol_touch.h File Reference
KGAPI "touch" protocol command parser declarations.
Macros
#define KG_PACKET_ID_CMD_TOUCH_GET_MODE 0x01
#define KG_PACKET_ID_CMD_TOUCH_SET_MODE 0x02
#define KG_PACKET_ID_EVT_TOUCH_MODE 0x01
#define KG_PACKET_ID_EVT_TOUCH_STATUS 0x02
Functions
uint16_t kg_cmd_touch_get_mode (uint8_t *mode)
Get the current touch mode.
uint16_t kg_cmd_touch_set_mode (uint8_t mode)
Set a new touch mode.
uint8_t process_protocol_command_touch (uint8_t *rxPacket)
Command processing routine for "touch" packet class.
Variables
uint8_t(* kg_evt_touch_mode)(uint8_t mode)
uint8_t(* kg_evt_touch_status)(uint8_t status_len, uint8_t *status_data)
Detailed Description
KGAPI "touch" protocol command parser declarations.
Author
Jeff Rowberg
Date
2014-11-03
This file implements subsystem-specific command processing functions for the "touch" part of the KGAPI protocol.
Normally it is not necessary to edit this file. (It is also autogenerated.)
Definition in file support_protocol_touch.h.
Function Documentation
uint16_t kg_cmd_touch_get_mode (uint8_t * mode)
Get the current touch mode.
Parameters
[out] mode Current touch mode setting
Returns
Result code (0=success)
Definition at line 211 of file support_touch.cpp.
Referenced by process_protocol_command_touch().
uint16_t kg_cmd_touch_set_mode (uint8_t mode)
Set a new touch mode.
Parameters
[in] mode New touch mode to set
Returns
Result code (0=success)
Definition at line 221 of file support_touch.cpp.
Referenced by process_protocol_command_touch().
uint8_t process_protocol_command_touch (uint8_t * rxPacket)
Command processing routine for "touch" packet class.
Parameters
[in] rxPacket Incoming KGAPI packet buffer
Returns
Protocol error, if any (0 for success)
See also
protocol_parse()
KGAPI command: kg_cmd_touch_get_mode()
KGAPI command: kg_cmd_touch_set_mode()
Definition at line 53 of file support_protocol_touch.cpp.
Referenced by protocol_parse().