Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_feedback_rgb.h File Reference
support_feedback_rgb.h File Reference
Feedback declarations for RGB LED.
Enumerations
enum feedback_rgb_mode_t {
KG_RGB_MODE_OFF = 0, KG_RGB_MODE_SOLID, KG_RGB_MODE_B200_100, KG_RGB_MODE_B200_50,
KG_RGB_MODE_B1000_500, KG_RGB_MODE_B1000_100, KG_RGB_MODE_B1000_100_2X, KG_RGB_MODE_B1000_100_3X,
KG_RGB_MODE_B3000_1000, KG_RGB_MODE_B3000_100, KG_RGB_MODE_B3000_100_2X, KG_RGB_MODE_B3000_100_3X,
KG_RGB_MODE_F200_100, KG_RGB_MODE_F200_50, KG_RGB_MODE_F1000_1000, KG_RGB_MODE_F1000_500,
KG_RGB_MODE_F1000_100, KG_RGB_MODE_F1000_100_2X, KG_RGB_MODE_F1000_100_3X, KG_RGB_MODE_F3000_3000,
KG_RGB_MODE_F3000_1000, KG_RGB_MODE_F3000_100, KG_RGB_MODE_F3000_100_2X, KG_RGB_MODE_F3000_100_3X,
KG_RGB_MODE_MAX
}
List of possible values for RGB mode.
Functions
void feedback_set_rgb_digital (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin digital logic states (red/green/blue)
void feedback_set_rgb_digital_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin digital logic state on one channel (red/green/blue)
void feedback_set_rgb_analog (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin analog PWM states (red/green/blue)
void feedback_set_rgb_analog_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin analog PWM state on one channel (red/green/blue)
void feedback_set_rgb_mode (feedback_rgb_mode_t r, feedback_rgb_mode_t g, feedback_rgb_mode_t b)
Sets RGB feedback modes (red/green/blue)
void setup_feedback_rgb ()
Initialize RGB feedback subsystem.
void update_feedback_rgb ()
Update status of RGB feedback subystem, called at 100Hz from loop()
Detailed Description
Feedback declarations for RGB LED.
Author
Jeff Rowberg
Date
2014-08-09
This file defines the feeback functionality for the RGB LED that may be included as an optional module in a Keyglove modular hardware design. This file is meant to contain only behavioral logic and abstracted functions that do not require specific pin knowledge of the selected MCU. Any pins used should be defined in the selected MCU board support file.
Normally it is not necessary to edit this file.
Definition in file support_feedback_rgb.h.
Enumeration Type Documentation
enum feedback_rgb_mode_t
List of possible values for RGB mode.
Enumerator
KG_RGB_MODE_OFF
(0) LED solid off
KG_RGB_MODE_SOLID
(1) LED solid on
KG_RGB_MODE_B200_100
(2) LED blinking with 200ms period, 100ms pulse
KG_RGB_MODE_B200_50
(3) LED blinking with 200ms period, 50ms pulse
KG_RGB_MODE_B1000_500
(4) LED blinking with 1sec period, 500ms pulse
KG_RGB_MODE_B1000_100
(5) LED blinking with 1sec period, 100ms pulse
KG_RGB_MODE_B1000_100_2X
(6) LED blinking with 1sec period, 100ms pulse 2x
KG_RGB_MODE_B1000_100_3X
(7) LED blinking with 1sec period, 100ms pulse 3x
KG_RGB_MODE_B3000_1000
(8) LED blinking with 3sec period, 1sec pulse
KG_RGB_MODE_B3000_100
(9) LED blinking with 3sec period, 100ms pulse
KG_RGB_MODE_B3000_100_2X
(10) LED blinking with 3sec period, 100ms pulse 2x
KG_RGB_MODE_B3000_100_3X
(11) LED blinking with 3sec period, 100ms pulse 3x
KG_RGB_MODE_F200_100
(12) LED fading with 200ms period, 100ms pulse
KG_RGB_MODE_F200_50
(13) LED fading with 200ms period, 50ms pulse
KG_RGB_MODE_F1000_1000
(14) LED fading with 1sec period, 500ms pulse
KG_RGB_MODE_F1000_500
(15) LED fading with 1sec period, 500ms pulse
KG_RGB_MODE_F1000_100
(16) LED fading with 1sec period, 100ms pulse
KG_RGB_MODE_F1000_100_2X
(17) LED fading with 1sec period, 100ms pulse 2x
KG_RGB_MODE_F1000_100_3X
(18) LED fading with 1sec period, 100ms pulse 3x
KG_RGB_MODE_F3000_3000
(19) LED fading with 3sec period, 3sec pulse
KG_RGB_MODE_F3000_1000
(20) LED fading with 3sec period, 1sec pulse
KG_RGB_MODE_F3000_100
(21) LED fading with 3sec period, 100ms pulse
KG_RGB_MODE_F3000_100_2X
(22) LED fading with 3sec period, 100ms pulse 2x
KG_RGB_MODE_F3000_100_3X
(23) LED fading with 3sec period, 100ms pulse 3x
Definition at line 49 of file support_feedback_rgb.h.
Function Documentation
void feedback_set_rgb_analog (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin analog PWM states (red/green/blue)
Parameters
[in] r Red: zero for off, non-zero for PWM (on), 255 for no change
[in] g Green: zero for off, non-zero for PWM (on), 255 for no change
[in] b Blue: zero for off, non-zero for PWM (on), 255 for no change
Definition at line 82 of file support_feedback_rgb.cpp.
void feedback_set_rgb_analog_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin analog PWM state on one channel (red/green/blue)
Parameters
[in] channel Channel number (0=RED, 1=GREEN, 2=BLUE)
[in] value PWM duty cycle (zero for off, non-zero for PWM/on)
Definition at line 93 of file support_feedback_rgb.cpp.
Referenced by update_feedback_rgb().
void feedback_set_rgb_digital (uint8_t r, uint8_t g, uint8_t b)
Sets RGB feedpack pin digital logic states (red/green/blue)
Parameters
[in] r Red: zero for low (off), non-zero for high (on), 255 for no change
[in] g Green: zero for low (off), non-zero for high (on), 255 for no change
[in] b Blue: zero for low (off), non-zero for high (on), 255 for no change
Definition at line 59 of file support_feedback_rgb.cpp.
Referenced by feedback_set_rgb_mode().
void feedback_set_rgb_digital_channel (uint8_t channel, uint8_t value)
Sets RGB feedpack pin digital logic state on one channel (red/green/blue)
Parameters
[in] channel Channel number (0=RED, 1=GREEN, 2=BLUE)
[in] value Logic state (zero for low/off, non-zero for high/on)
Definition at line 70 of file support_feedback_rgb.cpp.
Referenced by update_feedback_rgb().
void feedback_set_rgb_mode (feedback_rgb_mode_t r, feedback_rgb_mode_t g, feedback_rgb_mode_t b)
Sets RGB feedback modes (red/green/blue)
Parameters
[in] r Red mode
[in] g Green mode
[in] b Blue mode
Definition at line 105 of file support_feedback_rgb.cpp.
Referenced by kg_cmd_feedback_set_rgb_mode().