Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_feedback.cpp File Reference
support_feedback.cpp File Reference
General feedback support implementations.
#include "keyglove.h"
#include "support_feedback.h"
Functions
int16_t mod (int16_t x, int16_t m)
Modulo function that correctly handles negative values.
uint8_t square_wave (int32_t x, int32_t period, uint8_t duty)
Simple 1/0 square wave generator function.
int16_t triangle_wave (int32_t x, int32_t period, int32_t amplitude)
Simple triangle wave generator function.
Detailed Description
General feedback support implementations.
Author
Jeff Rowberg
Date
2014-11-07
This file provides the structural framework for feedback implementations in the overall Keyglove architecture.
Normally it is not necessary to edit this file.
Definition in file support_feedback.cpp.
Function Documentation
int16_t mod (int16_t x, int16_t m)
Modulo function that correctly handles negative values.
Parameters
[in] x Input value
[in] m Modulo constant
Returns
Calculated result on range [0, m-1]
Definition at line 51 of file support_feedback.cpp.
Referenced by square_wave(), and triangle_wave().
uint8_t square_wave (int32_t x, int32_t period, uint8_t duty)
Simple 1/0 square wave generator function.
Parameters
[in] x Input value
[in] period Period of full 1/0 cycle
[in] duty Duty cycle between 0 - 100 (%)
Returns
Output level (1=high, 0=low)
Definition at line 62 of file support_feedback.cpp.
Referenced by update_feedback_blink(), and update_feedback_rgb().
int16_t triangle_wave (int32_t x, int32_t period, int32_t amplitude)
Simple triangle wave generator function.
Parameters
[in] x Input value
[in] period Period of full cycle
[in] amplitude Full amplitude (100 will give range = [-50, +50])
Returns
Output value
This wave is aligned to exhibit the following pattern:
(0, 0)
(period/4, amplitude/2)
(period/2, 0)
(3period/4, -amplitude/2)
(period, 0)
Or in graphscii:
   |  A
   | / \
___|/___\_____ (period, 0)
   |     \   /
   |      \ /
   |       V
It can be shifted in either the X or Y dimension if necessary, but this form makes it easily useful for a number of different LED fading routines.
Definition at line 92 of file support_feedback.cpp.
Referenced by update_feedback_rgb().