Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_protocol_feedback.h File Reference
support_protocol_feedback.h File Reference
KGAPI "feedback" protocol command parser declarations.
Macros
#define KG_PACKET_ID_CMD_FEEDBACK_GET_BLINK_MODE 0x01
#define KG_PACKET_ID_CMD_FEEDBACK_SET_BLINK_MODE 0x02
#define KG_PACKET_ID_CMD_FEEDBACK_GET_PIEZO_MODE 0x03
#define KG_PACKET_ID_CMD_FEEDBACK_SET_PIEZO_MODE 0x04
#define KG_PACKET_ID_CMD_FEEDBACK_GET_VIBRATE_MODE 0x05
#define KG_PACKET_ID_CMD_FEEDBACK_SET_VIBRATE_MODE 0x06
#define KG_PACKET_ID_CMD_FEEDBACK_GET_RGB_MODE 0x07
#define KG_PACKET_ID_CMD_FEEDBACK_SET_RGB_MODE 0x08
#define KG_PACKET_ID_EVT_FEEDBACK_BLINK_MODE 0x01
#define KG_PACKET_ID_EVT_FEEDBACK_PIEZO_MODE 0x02
#define KG_PACKET_ID_EVT_FEEDBACK_VIBRATE_MODE 0x03
#define KG_PACKET_ID_EVT_FEEDBACK_RGB_MODE 0x04
Functions
uint16_t kg_cmd_feedback_get_blink_mode (uint8_t *mode)
Get current blink feedback mode.
uint16_t kg_cmd_feedback_set_blink_mode (uint8_t mode)
Set new blink feedback mode.
uint16_t kg_cmd_feedback_get_piezo_mode (uint8_t index, uint8_t *mode, uint8_t *duration, uint16_t *frequency)
Get current feedback mode for a piezo buzzer.
uint16_t kg_cmd_feedback_set_piezo_mode (uint8_t index, uint8_t mode, uint8_t duration, uint16_t frequency)
Set a new piezo feedback mode for a piezo buzzer.
uint16_t kg_cmd_feedback_get_vibrate_mode (uint8_t index, uint8_t *mode, uint8_t *duration)
Get current feedback mode for a vibration motor.
uint16_t kg_cmd_feedback_set_vibrate_mode (uint8_t index, uint8_t mode, uint8_t duration)
Set a new vibration motor feedback mode.
uint16_t kg_cmd_feedback_get_rgb_mode (uint8_t index, uint8_t *mode_red, uint8_t *mode_green, uint8_t *mode_blue)
Get current feedback mode for an RGB LED.
uint16_t kg_cmd_feedback_set_rgb_mode (uint8_t index, uint8_t mode_red, uint8_t mode_green, uint8_t mode_blue)
Set a new RGB LED feedback mode.
uint8_t process_protocol_command_feedback (uint8_t *rxPacket)
Command processing routine for "feedback" packet class.
Variables
uint8_t(* kg_evt_feedback_blink_mode)(uint8_t mode)
uint8_t(* kg_evt_feedback_piezo_mode)(uint8_t index, uint8_t mode, uint8_t duration, uint16_t frequency)
uint8_t(* kg_evt_feedback_vibrate_mode)(uint8_t index, uint8_t mode, uint8_t duration)
uint8_t(* kg_evt_feedback_rgb_mode)(uint8_t index, uint8_t mode_red, uint8_t mode_green, uint8_t mode_blue)
Detailed Description
KGAPI "feedback" protocol command parser declarations.
Author
Jeff Rowberg
Date
2014-11-03
This file implements subsystem-specific command processing functions for the "feedback" part of the KGAPI protocol.
Normally it is not necessary to edit this file. (It is also autogenerated.)
Definition in file support_protocol_feedback.h.
Function Documentation
uint16_t kg_cmd_feedback_get_blink_mode (uint8_t * mode)
Get current blink feedback mode.
Parameters
[out] mode Current blink feedback mode
Returns
Result code (0=success)
Definition at line 141 of file support_feedback_blink.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_get_piezo_mode (uint8_t index, uint8_t * mode, uint8_t * duration, uint16_t * frequency)
Get current feedback mode for a piezo buzzer.
Parameters
[in] index Index of piezo device for which to get the current mode
[out] mode Current feedback mode for specified piezo device
[out] duration Duration to maintain tone
[out] frequency Frequency of tone to generate
Returns
Result code (0=success)
Definition at line 121 of file support_feedback_piezo.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_get_rgb_mode (uint8_t index, uint8_t * mode_red, uint8_t * mode_green, uint8_t * mode_blue)
Get current feedback mode for an RGB LED.
Parameters
[in] index Index of RGB device for which to get the current mode
[out] mode_red Current feedback mode for specified RGB device red LED
[out] mode_green Current feedback mode for specified RGB device green LED
[out] mode_blue Current feedback mode for specified RGB device blue LED
Returns
Result code (0=success)
Definition at line 212 of file support_feedback_rgb.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_get_vibrate_mode (uint8_t index, uint8_t * mode, uint8_t * duration)
Get current feedback mode for a vibration motor.
Parameters
[in] index Index of vibration device for which to get the current mode
[out] mode Current feedback mode for specified vibration device
[out] duration Duration to maintain vibration
Returns
Result code (0=success)
Definition at line 111 of file support_feedback_vibrate.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_blink_mode (uint8_t mode)
Set new blink feedback mode.
Parameters
[in] mode New blink feedback mode to set
Returns
Result code (0=success)
Definition at line 151 of file support_feedback_blink.cpp.
Referenced by my_kg_evt_system_ready(), and process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_piezo_mode (uint8_t index, uint8_t mode, uint8_t duration, uint16_t frequency)
Set a new piezo feedback mode for a piezo buzzer.
Parameters
[in] index Index of piezo device for which to set a new mode
[in] mode New feedback mode to set for specified piezo device
[in] duration Duration to maintain tone
[in] frequency Frequency of tone to generate
Returns
Result code (0=success)
Definition at line 137 of file support_feedback_piezo.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_rgb_mode (uint8_t index, uint8_t mode_red, uint8_t mode_green, uint8_t mode_blue)
Set a new RGB LED feedback mode.
Parameters
[in] index Index of RGB device for which to set a new mode
[in] mode_red New feedback mode to set for specified RGB device red LED
[in] mode_green New feedback mode to set for specified RGB device green LED
[in] mode_blue New feedback mode to set for specified RGB device blue LED
Returns
Result code (0=success)
Definition at line 228 of file support_feedback_rgb.cpp.
Referenced by process_protocol_command_feedback().
uint16_t kg_cmd_feedback_set_vibrate_mode (uint8_t index, uint8_t mode, uint8_t duration)
Set a new vibration motor feedback mode.
Parameters
[in] index Index of vibration device for which to set a new mode
[in] mode New feedback mode to set for specified vibration device
[in] duration Duration to maintain vibration
Returns
Result code (0=success)
Definition at line 125 of file support_feedback_vibrate.cpp.
Referenced by process_protocol_command_feedback().
uint8_t process_protocol_command_feedback (uint8_t * rxPacket)
Command processing routine for "feedback" packet class.
Parameters
[in] rxPacket Incoming KGAPI packet buffer
Returns
Protocol error, if any (0 for success)
See also
protocol_parse()
KGAPI command: kg_cmd_feedback_get_blink_mode()
KGAPI command: kg_cmd_feedback_set_blink_mode()
KGAPI command: kg_cmd_feedback_get_piezo_mode()
KGAPI command: kg_cmd_feedback_set_piezo_mode()
KGAPI command: kg_cmd_feedback_get_vibrate_mode()
KGAPI command: kg_cmd_feedback_set_vibrate_mode()
KGAPI command: kg_cmd_feedback_get_rgb_mode()
KGAPI command: kg_cmd_feedback_set_rgb_mode()
Definition at line 59 of file support_protocol_feedback.cpp.
Referenced by protocol_parse().