Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_protocol_system.h File Reference
support_protocol_system.h File Reference
KGAPI "system" protocol command parser declarations.
Macros
#define KG_PACKET_ID_CMD_SYSTEM_PING 0x01
#define KG_PACKET_ID_CMD_SYSTEM_RESET 0x02
#define KG_PACKET_ID_CMD_SYSTEM_GET_INFO 0x03
#define KG_PACKET_ID_CMD_SYSTEM_GET_MEMORY 0x04
#define KG_PACKET_ID_CMD_SYSTEM_SET_TIMER 0x05
#define KG_PACKET_ID_CMD_SYSTEM_GET_BATTERY_STATUS 0x06
#define KG_PACKET_ID_EVT_SYSTEM_BOOT 0x01
#define KG_PACKET_ID_EVT_SYSTEM_READY 0x02
#define KG_PACKET_ID_EVT_SYSTEM_ERROR 0x03
#define KG_PACKET_ID_EVT_SYSTEM_TIMER_TICK 0x04
#define KG_PACKET_ID_EVT_SYSTEM_BATTERY_STATUS 0x05
#define KG_SYSTEM_RESET_TYPE_NORMAL 0x01
Reset all components (e.g. core, motion, Bluetooth)
#define KG_SYSTEM_RESET_TYPE_KGONLY 0x02
Reset only core Keyglove board.
Functions
uint16_t kg_cmd_system_ping (uint32_t *runtime)
Test communication with Keyglove device and get current runtime.
uint16_t kg_cmd_system_reset (uint8_t type)
Reset Keyglove device.
uint16_t kg_cmd_system_get_info (uint8_t *major, uint8_t *minor, uint8_t *patch, uint32_t *timestamp)
Get firmware build info.
uint16_t kg_cmd_system_get_memory (uint32_t *free_ram, uint32_t *total_ram)
Get system memory usage.
uint16_t kg_cmd_system_set_timer (uint8_t handle, uint16_t interval, uint8_t oneshot)
Set a timer interval to trigger future behavior.
uint16_t kg_cmd_system_get_battery_status (uint8_t *status, uint8_t *level)
Get battery status.
uint8_t process_protocol_command_system (uint8_t *rxPacket)
Command processing routine for "system" packet class.
Variables
uint8_t(* kg_evt_system_boot)(uint8_t major, uint8_t minor, uint8_t patch, uint32_t timestamp)
uint8_t(* kg_evt_system_ready)()
uint8_t(* kg_evt_system_error)(uint16_t code)
uint8_t(* kg_evt_system_timer_tick)(uint8_t handle, uint32_t seconds, uint8_t subticks)
uint8_t(* kg_evt_system_battery_status)(uint8_t status, uint8_t level)
Detailed Description
KGAPI "system" protocol command parser declarations.
Author
Jeff Rowberg
Date
2014-11-03
This file implements subsystem-specific command processing functions for the "system" part of the KGAPI protocol.
Normally it is not necessary to edit this file. (It is also autogenerated.)
Definition in file support_protocol_system.h.
Function Documentation
uint16_t kg_cmd_system_get_battery_status (uint8_t * status, uint8_t * level)
Get battery status.
Parameters
[out] status Battery status
[out] level Charge level (0-100)
Returns
Result code (0=success)
Definition at line 425 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_get_info (uint8_t * major, uint8_t * minor, uint8_t * patch, uint32_t * timestamp)
Get firmware build info.
Parameters
[out] major Firmware major version number
[out] minor Firmware minor version number
[out] patch Firmware patch version number
[out] timestamp Firmware build timestamp
Returns
Result code (0=success)
Definition at line 366 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_get_memory (uint32_t * free_ram, uint32_t * total_ram)
Get system memory usage.
Parameters
[out] free_ram Free RAM
[out] total_ram Total RAM
Returns
Result code (0=success)
Definition at line 380 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_ping (uint32_t * runtime)
Test communication with Keyglove device and get current runtime.
Parameters
[out] runtime Number of seconds since last boot/reset
Returns
Result code (0=success)
Definition at line 328 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_reset (uint8_t type)
Reset Keyglove device.
Parameters
[in] type Type of reset to perform
Returns
Result code (0=success)
Definition at line 338 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint16_t kg_cmd_system_set_timer (uint8_t handle, uint16_t interval, uint8_t oneshot)
Set a timer interval to trigger future behavior.
Parameters
[in] handle Timer handle (0-7)
[in] interval Interval (10ms units)
[in] oneshot Repeating (0) or one-shot (1)
Returns
Result code (0=success)
Definition at line 396 of file keyglove.cpp.
Referenced by process_protocol_command_system().
uint8_t process_protocol_command_system (uint8_t * rxPacket)
Command processing routine for "system" packet class.
Parameters
[in] rxPacket Incoming KGAPI packet buffer
Returns
Protocol error, if any (0 for success)
See also
protocol_parse()
KGAPI command: kg_cmd_system_ping()
KGAPI command: kg_cmd_system_reset()
KGAPI command: kg_cmd_system_get_info()
KGAPI command: kg_cmd_system_get_memory()
KGAPI command: kg_cmd_system_set_timer()
KGAPI command: kg_cmd_system_get_battery_status()
Definition at line 57 of file support_protocol_system.cpp.
Referenced by protocol_parse().