Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_touch.cpp File Reference
support_touch.cpp File Reference
General touch support implementations.
#include "keyglove.h"
#include "support_board.h"
#include "support_protocol.h"
#include "support_touch.h"
Functions
void setup_touch ()
Initialize touch detection system.
void update_touch ()
Update status of touch system, called at 100Hz from loop()
uint8_t touch_check_mode (uint8_t mode, uint8_t pos)
Check whether a certain mode is active in a certain position.
void touch_set_mode (uint8_t mode)
Set new active touch mode (replaces everything in mode stack)
void touch_push_mode (uint8_t mode)
Apply new touch mode to top of mode stack.
void touch_pop_mode ()
Remove last touch mode from top of mode stack.
void touch_toggle_mode (uint8_t mode)
Toggle touch mode in mode stack (push if missing, remove/pop if present)
uint16_t kg_cmd_touch_get_mode (uint8_t *mode)
Get the current touch mode.
uint16_t kg_cmd_touch_set_mode (uint8_t mode)
Set a new touch mode.
Variables
uint8_t touchMode
Touch mode.
uint8_t touchTick
Touch tick reference.
uint16_t opt_touch_detect_threshold = 20
OPTION: Milliseconds required for a touch to register as legitimate.
uint32_t touchTime
Touch detection reference timestamp.
uint8_t touches_now [4]
Immediate status of all touch combinations.
uint8_t touches_verify [4]
Previous status of all touch combinations (debouncing in progress)
uint8_t touches_active [4]
Registered (debounced) status of all touch combinations.
uint8_t touchModeStack [] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
Stackable touch mode tracking info.
uint8_t touchModeStackPos = 0
Current position in mode stack.
Detailed Description
General touch support implementations.
Author
Jeff Rowberg
Date
2014-11-07
This file provides the structural framework for touch implementations in the overall Keyglove architecture.
Normally it is not necessary to edit this file.
Definition in file support_touch.cpp.
Function Documentation
uint16_t kg_cmd_touch_get_mode (uint8_t * mode)
Get the current touch mode.
Parameters
[out] mode Current touch mode setting
Returns
Result code (0=success)
Definition at line 211 of file support_touch.cpp.
Referenced by process_protocol_command_touch().
uint16_t kg_cmd_touch_set_mode (uint8_t mode)
Set a new touch mode.
Parameters
[in] mode New touch mode to set
Returns
Result code (0=success)
Definition at line 221 of file support_touch.cpp.
Referenced by process_protocol_command_touch().
uint8_t touch_check_mode (uint8_t mode, uint8_t pos)
Check whether a certain mode is active in a certain position.
Parameters
mode Mode to check
pos Stack position to check
Definition at line 136 of file support_touch.cpp.
void touch_push_mode (uint8_t mode)
Apply new touch mode to top of mode stack.
Parameters
[in] mode New mode to push
Definition at line 160 of file support_touch.cpp.
Referenced by touch_toggle_mode().
void touch_set_mode (uint8_t mode)
Set new active touch mode (replaces everything in mode stack)
Parameters
[in] mode New mode to set
Definition at line 147 of file support_touch.cpp.
Referenced by kg_cmd_touch_set_mode(), and setup_touch().
void touch_toggle_mode (uint8_t mode)
Toggle touch mode in mode stack (push if missing, remove/pop if present)
Parameters
[in] mode Mode to toggle
Definition at line 184 of file support_touch.cpp.