Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_motion_mpu6050_hand.h File Reference
support_motion_mpu6050_hand.h File Reference
Motion support declarations for hand-mounted MPU-6050 sensor.
#include <I2Cdev.h>
#include <MPU6050.h>
#include "support_helper_3dmath.h"
Functions
void motion_mpu6050_hand_interrupt ()
Interrupt handler for INT pin from MPU-6050.
void motion_set_mpu6050_hand_mode (uint8_t mode)
Sets the MPU-6050 sensor mode.
void setup_motion_mpu6050_hand ()
Initialize MPU-6050 communications and interrupt handler.
void update_motion_mpu6050_hand ()
Update motion data from MPU-6050.
Variables
bool mpuHandInterrupt
Interrupt flag for motion data availability.
VectorInt16 aa
Filtered linear acceleration.
VectorInt16 gv
Filtered rotational velocity.
Detailed Description
Motion support declarations for hand-mounted MPU-6050 sensor.
Author
Jeff Rowberg
Date
2014-11-07
Definition in file support_motion_mpu6050_hand.h.
Function Documentation
void motion_mpu6050_hand_interrupt ()
Interrupt handler for INT pin from MPU-6050.
See also
mpuHandInterrupt
Definition at line 62 of file support_motion_mpu6050_hand.cpp.
Referenced by motion_set_mpu6050_hand_mode().
void motion_set_mpu6050_hand_mode (uint8_t mode)
Sets the MPU-6050 sensor mode.
Parameters
[in] mode Sensor mode (0=disabled, 1=enabled)
Definition at line 70 of file support_motion_mpu6050_hand.cpp.
Referenced by kg_cmd_motion_set_mode().
void setup_motion_mpu6050_hand ()
Initialize MPU-6050 communications and interrupt handler.
This function sets the MPU-6050 to 100Hz output, 2000 deg/sec resolution for the gyroscope, and enables a latching active-low interrupt on DRDY (raw data ready), MOT (motion detected), and ZMOT (zero motion detected).
Definition at line 92 of file support_motion_mpu6050_hand.cpp.
Referenced by setup().
void update_motion_mpu6050_hand ()
Update motion data from MPU-6050.
This function is called whenever the motion interrupt occurs and the flag is set by the interrupt handler, and then detected as such from inside the main loop() function. All six axes of raw data are read, then filtered and stored.
See also
API event: kg_evt_motion_data()
Definition at line 146 of file support_motion_mpu6050_hand.cpp.
Referenced by loop().