Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_hid_keyboard.cpp File Reference
support_hid_keyboard.cpp File Reference
HID keyboard helper function implementations.
#include "keyglove.h"
#include "support_hid_keyboard.h"
#include "support_bluetooth2_iwrap.h"
Functions
void setup_hid_keyboard ()
Initialize HID keyboard behavior.
void keyboard_key_down (uint8_t code)
Send key press (down) HID report.
void keyboard_key_up (uint8_t code)
Send key release (up) HID report.
void keyboard_key_press (uint8_t code)
Send keypress (down-up) HID reports.
void keyboard_modifier_down (uint8_t code)
Send modifier press (down) HID report.
void keyboard_modifier_up (uint8_t code)
Send modifier release (up) HID report.
void keyboard_modifier_toggle (uint8_t code)
Switch modifier state to opposite of what it was (down vs. up)
void keyboard_modifier_press (uint8_t code)
Send modifier keypress (down-up) HID reports.
Variables
uint8_t hidModifiersDown = 0
Modifier keys currently down.
uint8_t hidKeysDown [] = { 0, 0, 0, 0, 0, 0 }
Normal keys currently down.
Detailed Description
HID keyboard helper function implementations.
Author
Jeff Rowberg
Date
2014-11-07
This file provides supporting code for sending HID keyboard data to a connected wired or wireless host. This is only relevant if you have enabled normal HID support over USB or Bluetooth.
Normally it is not necessary to edit this file.
Definition in file support_hid_keyboard.cpp.
Function Documentation
void keyboard_key_down (uint8_t code)
Send key press (down) HID report.
Parameters
[in] code Key code
Definition at line 65 of file support_hid_keyboard.cpp.
Referenced by keyboard_key_press(), and my_kg_evt_touch_status().
void keyboard_key_press (uint8_t code)
Send keypress (down-up) HID reports.
Parameters
[in] code Modifier key bitmask
Definition at line 213 of file support_hid_keyboard.cpp.
Referenced by my_kg_evt_touch_status().
void keyboard_key_up (uint8_t code)
Send key release (up) HID report.
Parameters
[in] code Key code
Definition at line 138 of file support_hid_keyboard.cpp.
Referenced by keyboard_key_press(), and my_kg_evt_touch_status().
void keyboard_modifier_down (uint8_t code)
Send modifier press (down) HID report.
Parameters
[in] code Modifier key bitmask
Definition at line 225 of file support_hid_keyboard.cpp.
Referenced by keyboard_modifier_press(), and keyboard_modifier_toggle().
void keyboard_modifier_press (uint8_t code)
Send modifier keypress (down-up) HID reports.
Parameters
[in] code Modifier key bitmask
Definition at line 281 of file support_hid_keyboard.cpp.
void keyboard_modifier_toggle (uint8_t code)
Switch modifier state to opposite of what it was (down vs. up)
Parameters
[in] code Modifier key bitmask
Definition at line 267 of file support_hid_keyboard.cpp.
void keyboard_modifier_up (uint8_t code)
Send modifier release (up) HID report.
Parameters
[in] code Modifier key bitmask
Definition at line 245 of file support_hid_keyboard.cpp.
Referenced by keyboard_modifier_press(), and keyboard_modifier_toggle().