Keyglove: C:/Users/rowbeje/Documents/Github/keyglove/keyglove/support_motion.cpp File Reference
support_motion.cpp File Reference
General motion support implementations.
#include "keyglove.h"
#include "support_protocol.h"
#include "support_motion.h"
Functions
uint16_t kg_cmd_motion_get_mode (uint8_t index, uint8_t *mode)
Get current mode for specified motion sensor.
uint16_t kg_cmd_motion_set_mode (uint8_t index, uint8_t mode)
Set new mode for specified motion sensor.
Variables
motion_mode_t motionMode [1]
Motion sensor modes.
Detailed Description
General motion support implementations.
Author
Jeff Rowberg
Date
2014-11-07
This file provides the structural framework for motion implementations in the overall Keyglove architecture.
Normally it is not necessary to edit this file.
Definition in file support_motion.cpp.
Function Documentation
uint16_t kg_cmd_motion_get_mode (uint8_t index, uint8_t * mode)
Get current mode for specified motion sensor.
Parameters
[in] index Index of motion sensor for which to get the current mode
[out] mode Current motion sensor mode
Returns
Result code (0=success)
Definition at line 56 of file support_motion.cpp.
Referenced by process_protocol_command_motion().
uint16_t kg_cmd_motion_set_mode (uint8_t index, uint8_t mode)
Set new mode for specified motion sensor.
Parameters
[in] index Index of motion sensor for which to get the current mode
[in] mode New motion sensor mode to set
Returns
Result code (0=success)
Definition at line 71 of file support_motion.cpp.
Referenced by my_kg_evt_touch_status(), and process_protocol_command_motion().