// Keyglove controller source code - KGAPI "motion" protocol command parser implementation
// 2015-07-03 by Jeff Rowberg <jeff@rowberg.net>

/*
================================================================================
Keyglove source code is placed under the MIT license
Copyright (c) 2015 Jeff Rowberg

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

================================================================================
*/

/**
 * @file support_protocol_motion.cpp
 * @brief KGAPI "motion" protocol command parser implementation
 * @author Jeff Rowberg
 * @date 2015-07-03
 *
 * This file implements subsystem-specific command processing functions for the
 * "motion" part of the KGAPI protocol.
 *
 * This file is autogenerated. Normally it is not necessary to edit this file.
 */

#include "keyglove.h"
#include "support_motion.h"
#include "support_protocol.h"
#include "support_protocol_motion.h"

/**
 * @brief Command processing routine for "motion" packet class
 * @param[in] rxPacket Incoming KGAPI packet buffer
 * @return Protocol error, if any (0 for success)
 * @see protocol_parse()
 * @see KGAPI command: kg_cmd_motion_get_mode()
 * @see KGAPI command: kg_cmd_motion_set_mode()
 */
uint8_t process_protocol_command_motion(uint8_t *rxPacket) {
    // check for valid command IDs
    uint8_t protocol_error = 0;
    switch (rxPacket[3]) {
        case KG_PACKET_ID_CMD_MOTION_GET_MODE: // 0x01
            // motion_get_mode(uint8_t index)(uint8_t mode)
            // parameters = 1 byte
            if (rxPacket[1] != 1) {
                // incorrect parameter length
                protocol_error = KG_PROTOCOL_ERROR_PARAMETER_LENGTH;
            } else {
                // run command
                uint8_t mode = 0;
                /*uint16_t result =*/ kg_cmd_motion_get_mode(rxPacket[4], &mode);
        
                // build response
                uint8_t payload[1] = { mode };
        
                // send response
                send_keyglove_packet(KG_PACKET_TYPE_COMMAND, 1, rxPacket[2], rxPacket[3], payload);
            }
            break;
        
        case KG_PACKET_ID_CMD_MOTION_SET_MODE: // 0x02
            // motion_set_mode(uint8_t index, uint8_t mode)(uint16_t result)
            // parameters = 2 bytes
            if (rxPacket[1] != 2) {
                // incorrect parameter length
                protocol_error = KG_PROTOCOL_ERROR_PARAMETER_LENGTH;
            } else {
                // run command
                uint16_t result = kg_cmd_motion_set_mode(rxPacket[4], rxPacket[5]);
        
                // build response
                uint8_t payload[2] = { (uint8_t)(result & 0xFF), (uint8_t)((result >> 8) & 0xFF) };
        
                // send response
                send_keyglove_packet(KG_PACKET_TYPE_COMMAND, 2, rxPacket[2], rxPacket[3], payload);
            }
            break;
        
        default:
            protocol_error = KG_PROTOCOL_ERROR_INVALID_COMMAND;
    }
    return protocol_error;
}

/* ============================= */
/* KGAPI COMMAND IMPLEMENTATIONS */
/* ============================= */

/**
 * @brief Get current mode for specified motion sensor
 * @param[in] index Index of motion sensor for which to get the current mode
 * @param[out] mode Current motion sensor mode
 * @return Result code (0=success)
 */
uint16_t kg_cmd_motion_get_mode(uint8_t index, uint8_t *mode) {
    if (index >= KG_MOTION_SENSOR_COUNT) {
        return KG_PROTOCOL_ERROR_PARAMETER_RANGE;
    } else {
        *mode = motionMode[index];
    }
    return 0; // success
}

/**
 * @brief Set new mode for specified motion sensor
 * @param[in] index Index of motion sensor for which to get the current mode
 * @param[in] mode New motion sensor mode to set
 * @return Result code (0=success)
 */
uint16_t kg_cmd_motion_set_mode(uint8_t index, uint8_t mode) {
    if (index >= KG_MOTION_SENSOR_COUNT || mode >= KG_MOTION_MODE_MAX) {
        return KG_PROTOCOL_ERROR_PARAMETER_RANGE;
    } else {
        //motion_set_mode((motion_mode_t)mode);
        #if KG_MOTION & KG_MOTION_MPU6050_HAND
            if (index == 0) {
                motion_set_mpu6050_hand_mode(mode);
            }
        #endif // KG_MOTION & KG_MOTION_MPU6050_HAND

        // send kg_evt_feedback_vibrate_mode packet (if we aren't setting it from an API command)
        if (!inBinPacket) {
            uint8_t payload[2] = { index, mode };
            skipPacket = 0;
            if (kg_evt_motion_mode) skipPacket = kg_evt_motion_mode(index, mode);
            if (!skipPacket) send_keyglove_packet(KG_PACKET_TYPE_EVENT, 2, KG_PACKET_CLASS_MOTION, KG_PACKET_ID_EVT_MOTION_MODE, payload);
        }
    }
    return 0; // success
}

/* ==================== */
/* KGAPI EVENT POINTERS */
/* ==================== */

/* 0x01 */ uint8_t (*kg_evt_motion_mode)(uint8_t index, uint8_t mode);
/* 0x02 */ uint8_t (*kg_evt_motion_data)(uint8_t index, uint8_t flags, uint8_t data_len, uint8_t *data_data);
/* 0x03 */ uint8_t (*kg_evt_motion_state)(uint8_t index, uint8_t state);
